# Generated by Django 6.0.1 on 2026-02-09 15:45

from django.db import migrations


def add_stringers_menu_item(apps, schema_editor):
    """Добавить пункт меню 'Стрингеры'."""
    MenuItem = apps.get_model("navigation", "MenuItem")
    MenuItem.objects.get_or_create(
        url="/stringers/",
        defaults={"title": "Стрингеры", "order": 12, "is_active": True},
    )


def create_stringer_page(apps, schema_editor):
    """Создать singleton StringerPage."""
    StringerPage = apps.get_model("content", "StringerPage")
    StringerPage.objects.get_or_create(
        pk=1,
        defaults={
            "title": "Стрингеры",
            "description": "",
            "is_enabled": True,
        },
    )


def reverse_add_stringers_menu_item(apps, schema_editor):
    """Удалить пункт меню 'Стрингеры'."""
    MenuItem = apps.get_model("navigation", "MenuItem")
    MenuItem.objects.filter(url="/stringers/").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0008_add_rules_menu_item'),
        ('content', '0014_add_stringer_models'),
    ]

    operations = [
        migrations.RunPython(add_stringers_menu_item, reverse_add_stringers_menu_item),
        migrations.RunPython(create_stringer_page, migrations.RunPython.noop),
    ]
