# Generated by Django 6.0.1 on 2026-01-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadToHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_wins', models.PositiveIntegerField(default=0, verbose_name='Победы П1')),
                ('player2_wins', models.PositiveIntegerField(default=0, verbose_name='Победы П2')),
            ],
            options={
                'verbose_name': 'Личная встреча',
                'verbose_name_plural': 'Личные встречи',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(blank=True, max_length=50, verbose_name='Раунд')),
                ('player1_set1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='П1 Сет 1')),
                ('player2_set1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='П2 Сет 1')),
                ('player1_set2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='П1 Сет 2')),
                ('player2_set2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='П2 Сет 2')),
                ('player1_set3', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='П1 Сет 3')),
                ('player2_set3', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='П2 Сет 3')),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('completed_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('in_progress', 'В процессе'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('walkover', 'Без игры')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('points_player1', models.IntegerField(default=0, verbose_name='Очки П1')),
                ('points_player2', models.IntegerField(default=0, verbose_name='Очки П2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['-scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SeasonRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20, verbose_name='Сезон')),
                ('category', models.CharField(choices=[('futures', 'Futures'), ('base', 'Base'), ('tour', 'Tour'), ('hard', 'Hard'), ('challenger', 'Challenger'), ('masters', 'Masters')], max_length=20, verbose_name='Категория')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Рейтинг сезона',
                'verbose_name_plural': 'Рейтинги сезонов',
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('city', models.CharField(choices=[('moscow', 'Москва'), ('spb', 'Санкт-Петербург')], default='moscow', max_length=20, verbose_name='Город')),
                ('category', models.CharField(choices=[('futures', 'Futures'), ('base', 'Base'), ('tour', 'Tour'), ('hard', 'Hard'), ('challenger', 'Challenger'), ('masters', 'Masters')], default='base', max_length=20, verbose_name='Категория')),
                ('tournament_type', models.CharField(choices=[('regular', 'Регулярный'), ('playoff', 'Плей-офф'), ('champions', 'Лига чемпионов'), ('challenger', 'Challenger')], default='regular', max_length=20, verbose_name='Тип турнира')),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящий'), ('active', 'Активный'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='upcoming', max_length=20, verbose_name='Статус')),
                ('points_multiplier', models.IntegerField(default=100, verbose_name='Множитель очков')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн регистрации')),
                ('image', models.ImageField(blank=True, upload_to='tournaments/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['-start_date'],
            },
        ),
    ]
