# Generated by Django 6.0.1 on 2026-01-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='duration',
            field=models.CharField(choices=[('single', 'Однодневный'), ('weekend', 'Выходного дня'), ('multi', 'Многодневный')], default='multi', max_length=10, verbose_name='Продолжительность'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужчины'), ('female', 'Женщины'), ('mixed', 'Смешанный')], default='male', max_length=10, verbose_name='Категория по полу'),
        ),
    ]
