# Generated by Django 6.0.1 on 2026-01-22 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_duration_tournament_gender'),
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResultProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('win', 'Победа'), ('loss', 'Поражение'), ('walkover_win', 'Тех. победа'), ('walkover_loss', 'Тех. поражение')], default='win', max_length=20, verbose_name='Результат')),
                ('player1_set1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='П1 Сет 1')),
                ('player2_set1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='П2 Сет 1')),
                ('player1_set2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='П1 Сет 2')),
                ('player2_set2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='П2 Сет 2')),
                ('player1_set3', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='П1 Сет 3')),
                ('player2_set3', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='П2 Сет 3')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('accepted', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_proposals', to='tournaments.match', verbose_name='Матч')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_results', to='users.player', verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Предложенный результат',
                'verbose_name_plural': 'Предложенные результаты',
                'ordering': ['-created_at'],
            },
        ),
    ]
