# Generated by Django 6.0.1 on 2026-01-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_matchresultproposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='points_multiplier',
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_loser',
            field=models.IntegerField(default=-50, verbose_name='Очки за проигрыш'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_winner',
            field=models.IntegerField(default=100, verbose_name='Очки за победу'),
        ),
    ]
