# Generated by Django 6.0.1 on 2026-01-30 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_fan_bracket_and_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('cover_image', models.ImageField(blank=True, help_text='Если пусто и турнир привязан — используется изображение турнира.', upload_to='schedule/', verbose_name='Обложка / баннер')),
                ('type_badge', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('open', 'Open'), ('cup', 'Cup')], default='open', max_length=20, verbose_name='Тип турнира')),
                ('status_override', models.CharField(blank=True, choices=[('reg_open', 'Регистрация открыта'), ('reg_closed', 'Регистрация закрыта'), ('in_progress', 'Турнир идёт'), ('completed', 'Завершён')], help_text='Если пусто — определяется по турниру.', max_length=20, verbose_name='Статус (переопределение)')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание (2–3 строки)')),
                ('registration_until', models.DateField(blank=True, null=True, verbose_name='Регистрация до')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Старт турнира')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('format_type', models.CharField(choices=[('singles', 'Одиночный'), ('doubles', 'Парный')], default='singles', max_length=20, verbose_name='Формат')),
                ('bracket_size', models.CharField(blank=True, help_text='Например: 16 игроков, 32 игрока', max_length=50, verbose_name='Сетка')),
                ('match_format', models.CharField(blank=True, help_text='Например: 1 сет до 6, 2 сета + тай-брейк', max_length=100, verbose_name='Формат матчей')),
                ('surface', models.CharField(blank=True, choices=[('hard', 'Hard'), ('clay', 'Clay'), ('indoor', 'Indoor')], max_length=20, verbose_name='Покрытие')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. участников (для ручной карточки)')),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Взнос (руб)')),
                ('show_fee', models.BooleanField(default=True, verbose_name='Показывать взнос')),
                ('show_prizes', models.BooleanField(default=False, verbose_name='Показывать призы')),
                ('show_sponsors', models.BooleanField(default=False, verbose_name='Показывать спонсоров')),
                ('show_location', models.BooleanField(default=True, verbose_name='Показывать локацию')),
                ('prizes_text', models.TextField(blank=True, help_text='Например: 1 место — Кубок + 100 очков', verbose_name='Призы (текст)')),
                ('location_name', models.CharField(blank=True, max_length=200, verbose_name='Название клуба')),
                ('location_address', models.TextField(blank=True, verbose_name='Адрес')),
                ('map_url', models.URLField(blank=True, verbose_name='Ссылка на карту')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_cards', to='tournaments.tournament', verbose_name='Турнир (если привязан — данные берутся из него)')),
            ],
            options={
                'verbose_name': 'Карточка расписания',
                'verbose_name_plural': 'Расписание матчей',
                'ordering': ['-is_archived', 'order', 'start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatchScheduleSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, upload_to='schedule/sponsors/', verbose_name='Логотип')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='tournaments.matchscheduleitem', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Спонсор',
                'verbose_name_plural': 'Спонсоры',
                'ordering': ['order', 'id'],
            },
        ),
    ]
