# Generated by Django 6.0.1 on 2026-02-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_add_round_robin_format'),
        ('users', '0016_create_bye_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.PositiveIntegerField(blank=True, help_text='Для парных: обязателен. Количество команд (пар) для регистрации.', null=True, verbose_name='Максимальное количество команд'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='variant',
            field=models.CharField(choices=[('singles', 'Одиночный'), ('doubles', 'Парный')], default='singles', help_text='Одиночный: 1 на 1. Парный: команды по 2 человека.', max_length=20, verbose_name='Вариант'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(blank=True, help_text='Для одиночных: игрок 1. Для парных: первый игрок команды 1 (player1 из team1).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='users.player', verbose_name='Игрок 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(blank=True, help_text='Для одиночных: игрок 2. Для парных: первый игрок команды 2 (player1 из team2).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='users.player', verbose_name='Игрок 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Для парных: один из игроков победившей команды.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won_rel', to='users.player', verbose_name='Победитель'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bracket_generated',
            field=models.BooleanField(default=False, help_text='Сетка создана, участники зафиксированы, регистрация закрыта.', verbose_name='Сетка сформирована'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='match_days_per_round',
            field=models.PositiveSmallIntegerField(default=7, help_text='Сколько дней у игроков на проведение матча раунда/тура.', verbose_name='Дней на раунд (дедлайн матча)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Для одиночных: обязателен для FAN и круговых. Оставьте пустым для неограниченного.', null=True, verbose_name='Максимальное количество участников'),
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubles_teams_as_player1', to='users.player', verbose_name='Игрок 1')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubles_teams_as_player2', to='users.player', verbose_name='Игрок 2 (партнёр)')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Команда турнира',
                'verbose_name_plural': 'Команды турниров',
                'ordering': ['created_at'],
                'unique_together': {('tournament', 'player1')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='tournaments.tournamentteam', verbose_name='Команда 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='tournaments.tournamentteam', verbose_name='Команда 2'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='tournaments.tournamentteam', verbose_name='Победившая команда'),
        ),
    ]
