# Generated by Django 6.0.1 on 2026-02-05 14:26

import config.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_remove_tournament_category'),
        ('users', '0017_add_deadline_extension_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, upload_to='tournaments/', validators=[config.validators.validate_image_max_2mb], verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='DeadlineExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_extension_requests', to='tournaments.match', verbose_name='Матч')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_extension_requests', to='users.player', verbose_name='Кто запросил')),
            ],
            options={
                'verbose_name': 'Запрос продления дедлайна',
                'verbose_name_plural': 'Запросы продления дедлайна',
                'ordering': ['-created_at'],
            },
        ),
    ]
