# Generated by Django 6.0.1 on 2026-02-11 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0026_add_season_points'),
        ('users', '0022_set_is_verified_default_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(help_text="'Зима' или 'Лето'", max_length=20, verbose_name='Название сезона')),
                ('season_year', models.IntegerField(help_text='Год сезона (для зимы - год начала, для лета - текущий год)', verbose_name='Год сезона')),
                ('final_points', models.PositiveIntegerField(help_text='Количество FAN очков, накопленных за сезон', verbose_name='Итоговые очки')),
                ('final_rank', models.PositiveIntegerField(blank=True, help_text='Место игрока в рейтинге сезона', null=True, verbose_name='Итоговое место')),
                ('archived_at', models.DateTimeField(auto_now_add=True, help_text='Когда сезон был завершён и результаты заархивированы', verbose_name='Дата архивации')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_archives', to='users.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Архив сезона',
                'verbose_name_plural': 'Архивы сезонов',
                'ordering': ['-season_year', '-season_name', '-final_points'],
                'indexes': [models.Index(fields=['season_name', 'season_year', '-final_points'], name='tournaments_season__b9f545_idx')],
                'unique_together': {('player', 'season_name', 'season_year')},
            },
        ),
    ]
