# Generated by Django 6.0.1 on 2026-02-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0030_add_open_gender_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tournamentplayerresult",
            options={
                "ordering": ["-fan_points"],
                "verbose_name": "Результат в турнире",
                "verbose_name_plural": "Результаты в турнирах",
            },
        ),
        migrations.AlterField(
            model_name="match",
            name="deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="До этой даты матч должен быть сыгран (одноэтапная сетка).",
                null=True,
                verbose_name="Дедлайн матча",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="round_index",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Для сортировки и начисления сезонных очков.",
                verbose_name="Индекс раунда (1=1 круг, 2=2 круг, …)",
            ),
        ),
        migrations.AlterField(
            model_name="seasonarchive",
            name="final_points",
            field=models.PositiveIntegerField(
                help_text="Количество сезонных очков, накопленных за сезон",
                verbose_name="Итоговые очки",
            ),
        ),
        migrations.AlterField(
            model_name="seasonpoints",
            name="current_season_points",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Сезонные очки, накопленные в текущем сезоне. Сбрасываются в конце сезона.",
                verbose_name="Очки текущего сезона",
            ),
        ),
        migrations.AlterField(
            model_name="seasonrating",
            name="category",
            field=models.CharField(
                choices=[
                    ("novice", "Новичок"),
                    ("amateur", "Любитель"),
                    ("experienced", "Опытный"),
                    ("advanced", "Мастерс"),
                    ("professional", "Профессионал"),
                ],
                max_length=20,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="fan_points_final",
            field=models.PositiveSmallIntegerField(
                default=70, verbose_name="Очки финалисту"
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="fan_points_r1",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="Очки за 1 круг"
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="fan_points_r2",
            field=models.PositiveSmallIntegerField(
                default=25, verbose_name="Очки за 2 круг"
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="fan_points_sf",
            field=models.PositiveSmallIntegerField(
                default=45, verbose_name="Очки за полуфинал"
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="fan_points_winner",
            field=models.PositiveSmallIntegerField(
                default=100, verbose_name="Очки победителю"
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="max_participants",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Для одиночных: обязателен для одноэтапной сетки и круговых. Оставьте пустым для неограниченного.",
                null=True,
                verbose_name="Максимальное количество участников",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="points_loser",
            field=models.IntegerField(
                default=-50,
                help_text="Используется для круговых и других форматов (не одноэтапная/Олимпийская). Для кругового по умолчанию: 0 очков (можно настроить отрицательные, например -1). Для других форматов: -50 очков (очки отнимаются). Одноэтапная сетка и Олимпийская система используют только положительные очки за раунды/места.",
                verbose_name="Очки за проигрыш",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="points_winner",
            field=models.IntegerField(
                default=100,
                help_text="Используется для круговых и других форматов (не одноэтапная/Олимпийская). Для кругового по умолчанию: 1 очко. Для других форматов: 100 очков.",
                verbose_name="Очки за победу",
            ),
        ),
        migrations.AlterField(
            model_name="tournamentallowedcategory",
            name="category",
            field=models.CharField(
                choices=[
                    ("novice", "Новичок"),
                    ("amateur", "Любитель"),
                    ("experienced", "Опытный"),
                    ("advanced", "Мастерс"),
                    ("professional", "Профессионал"),
                ],
                max_length=20,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="tournamentplayerresult",
            name="fan_points",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Начислено сезонных очков"
            ),
        ),
    ]
