# Generated by Django 6.0.1 on 2026-02-17 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0031_alter_tournamentplayerresult_options_and_more"),
        ("users", "0024_alter_player_total_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="partner1",
            field=models.ForeignKey(
                blank=True,
                help_text="Для парного спарринга: второй игрок команды 1.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_as_partner1",
                to="users.player",
                verbose_name="Партнёр стороны 1",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="partner2",
            field=models.ForeignKey(
                blank=True,
                help_text="Для парного спарринга: второй игрок команды 2.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_as_partner2",
                to="users.player",
                verbose_name="Партнёр стороны 2",
            ),
        ),
    ]
