# Generated by Django 6.0.1 on 2026-02-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0032_add_partner1_partner2_for_doubles_sparring"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает участников"),
                    ("scheduled", "Запланирован"),
                    ("in_progress", "В процессе"),
                    ("completed", "Завершён"),
                    ("cancelled", "Отменён"),
                    ("walkover", "Без игры"),
                ],
                default="scheduled",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
