# Generated by Django 6.0.1 on 2026-02-23 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0033_alter_match_status"),
        ("users", "0025_update_ntrp_default_to_1_5"),
    ]

    operations = [
        migrations.CreateModel(
            name="TVDTournament",
            fields=[],
            options={
                "verbose_name": "ТВД-турнир",
                "verbose_name_plural": "Турниры выходного дня",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tournaments.tournament",),
        ),
        migrations.AlterModelOptions(
            name="tournament",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Турнир",
                "verbose_name_plural": "Многодневные Турниры",
            },
        ),
        migrations.AddField(
            model_name="match",
            name="tvd_stage",
            field=models.CharField(
                blank=True,
                help_text="group, main_qf, main_sf, main_final, third_place, consolation_sf, consolation_final",
                max_length=30,
                verbose_name="Этап ТВД",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="format",
            field=models.CharField(
                choices=[
                    ("single_elimination", "Одноэтапная сетка"),
                    ("olympic_consolation", "Олимпийская система (утешительная сетка)"),
                    ("round_robin", "Круговой"),
                    ("weekend_day", "Турнир выходного дня"),
                ],
                default="single_elimination",
                help_text="Одноэтапная сетка: турнир на выбывание с подвалом, посев по рейтингу, очки при вылете. \nКруговой: все играют со всеми, итоговая таблица по очкам.",
                max_length=20,
                verbose_name="Формат",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Предстоящий"),
                    ("active", "Активный"),
                    ("group_stage", "Групповой этап"),
                    ("playoffs", "Плей-офф"),
                    ("completed", "Завершён"),
                    ("cancelled", "Отменён"),
                ],
                default="upcoming",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.CreateModel(
            name="TVDGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=10, verbose_name="Название группы"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Группа завершена"),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tvd_groups",
                        to="tournaments.tournament",
                        verbose_name="Турнир",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа ТВД",
                "verbose_name_plural": "Группы ТВД",
                "ordering": ["tournament", "order", "name"],
                "unique_together": {("tournament", "name")},
            },
        ),
        migrations.AddField(
            model_name="match",
            name="tvd_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Для матчей группового этапа ТВД.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches",
                to="tournaments.tvdgroup",
                verbose_name="Группа ТВД",
            ),
        ),
        migrations.CreateModel(
            name="TVDGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seed",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Номер посева (1 = сильнейший в группе).",
                        null=True,
                        verbose_name="Посев",
                    ),
                ),
                ("wins", models.PositiveIntegerField(default=0, verbose_name="Победы")),
                (
                    "losses",
                    models.PositiveIntegerField(default=0, verbose_name="Поражения"),
                ),
                (
                    "games_won",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Геймов выиграно"
                    ),
                ),
                (
                    "games_lost",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Геймов проиграно"
                    ),
                ),
                (
                    "final_place",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1, 2, 3 (или 4 для групп по 4 человека).",
                        null=True,
                        verbose_name="Место в группе",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="tournaments.tvdgroup",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tvd_group_memberships",
                        to="users.player",
                        verbose_name="Игрок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник группы ТВД",
                "verbose_name_plural": "Участники групп ТВД",
                "ordering": ["group", "final_place", "seed"],
                "unique_together": {("group", "player")},
            },
        ),
    ]
