# Generated by Django 6.0.1 on 2026-02-23 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0034_tvd_models"),
        ("users", "0025_update_ntrp_default_to_1_5"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tvdgroupmember",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="tvdgroupmember",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Для парного ТВД. Для одиночного — используйте player.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tvd_group_memberships",
                to="tournaments.tournamentteam",
                verbose_name="Команда",
            ),
        ),
        migrations.AlterField(
            model_name="tvdgroupmember",
            name="player",
            field=models.ForeignKey(
                blank=True,
                help_text="Для одиночного ТВД. Для парного — используйте team.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tvd_group_memberships",
                to="users.player",
                verbose_name="Игрок",
            ),
        ),
        migrations.AddConstraint(
            model_name="tvdgroupmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("player__isnull", False)),
                fields=("group", "player"),
                name="tvdgroupmember_unique_group_player",
            ),
        ),
        migrations.AddConstraint(
            model_name="tvdgroupmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("team__isnull", False)),
                fields=("group", "team"),
                name="tvdgroupmember_unique_group_team",
            ),
        ),
    ]
