# Generated by Django 6.0.1 on 2026-02-25 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0007_surface_free_text"),
        ("tournaments", "0037_add_entry_refund_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="court",
            field=models.ForeignKey(
                blank=True,
                help_text="Площадка проведения турнира (опционально).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments",
                to="courts.court",
                verbose_name="Корт",
            ),
        ),
    ]
