# Generated by Django 6.0.1 on 2026-02-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0038_add_tournament_court"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tvdtournament",
            options={
                "verbose_name": "Однодневный турнир",
                "verbose_name_plural": "Однодневные турниры",
            },
        ),
        migrations.AlterField(
            model_name="tournament",
            name="format",
            field=models.CharField(
                choices=[
                    ("single_elimination", "Олимпийский (до 1 поражения)"),
                    ("olympic_consolation", "Олимпийский (за все места)"),
                    ("round_robin", "Круговой"),
                    ("weekend_day", "Однодневный турнир"),
                ],
                default="single_elimination",
                help_text="Одноэтапная сетка: турнир на выбывание с подвалом, посев по рейтингу, очки при вылете. \nКруговой: все играют со всеми, итоговая таблица по очкам.",
                max_length=20,
                verbose_name="Формат",
            ),
        ),
    ]
