# Generated by Django 6.0.1 on 2026-03-14 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
        ("tournaments", "0041_alter_tournamentphoto_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="points_loser",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="points_winner",
        ),
        migrations.AddField(
            model_name="tournament",
            name="club",
            field=models.ForeignKey(
                blank=True,
                help_text="Клуб-организатор (пусто — общий турнир платформы).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments",
                to="clubs.club",
                verbose_name="Клуб",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="is_open_interclub",
            field=models.BooleanField(
                default=False,
                help_text="Другие клубы могут подавать заявки на участие (только тариф Про).",
                verbose_name="Открытый межклубный",
            ),
        ),
    ]
