# Generated by Django 6.0.1 on 2026-04-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0042_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Мужчины"),
                    ("female", "Женщины"),
                    ("open", "Любой"),
                    ("mixed", "Микст"),
                ],
                default="male",
                help_text="Мужчины/Женщины — только указанный пол. Любой — любой пол (М против Ж, пары ММ против ЖЖ и т.д.). Микст — только для парных: в команде должны быть М + Ж.",
                max_length=10,
                verbose_name="Категория по полу",
            ),
        ),
    ]
