# Generated by Django 6.0.1 on 2026-04-23 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0043_club_tournament_proxy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tournamentallowedcategory",
            options={
                "ordering": [],
                "verbose_name": "Допустимая категория турнира",
                "verbose_name_plural": "Допустимые категории турнира",
            },
        ),
        migrations.AddField(
            model_name="tournament",
            name="allow_postpayment",
            field=models.BooleanField(
                default=False,
                help_text="Разрешить регистрацию без немедленной оплаты вступительного взноса. После дедлайна участникам без оплаты отправляется ссылка и даётся 12 часов.",
                verbose_name="Постоплата",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="postpayment_deadline_hours",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="Через сколько часов после запуска окна неоплатившие удаляются.",
                verbose_name="Длительность окна постоплаты (часы)",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="postpayment_window_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда запущено 12-часовое окно оплаты для участников без оплаты.",
                null=True,
                verbose_name="Старт окна постоплаты",
            ),
        ),
        migrations.CreateModel(
            name="TournamentPostpaymentInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Сумма (руб)",
                    ),
                ),
                ("due_at", models.DateTimeField(verbose_name="Оплатить до")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Оплачено"
                    ),
                ),
                (
                    "reminder_1h_sent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Отправлено напоминание за 1 час",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("paid", "Оплачен"),
                            ("expired", "Просрочен"),
                            ("cancelled", "Отменён"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "yookassa_payment_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="ID платежа YooKassa"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postpayment_invoices",
                        to="tournaments.tournament",
                        verbose_name="Турнир",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_postpayment_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инвойс постоплаты турнира",
                "verbose_name_plural": "Инвойсы постоплаты турниров",
                "unique_together": {("tournament", "user")},
            },
        ),
        migrations.CreateModel(
            name="TournamentRegistrationCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coverage_type",
                    models.CharField(
                        choices=[
                            ("subscription_slot", "Слот подписки"),
                            ("club_plan_slot", "Слот клубного тарифа"),
                            ("admin_granted", "Выдано администратором"),
                        ],
                        max_length=32,
                        verbose_name="Тип покрытия",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_coverages",
                        to="tournaments.tournament",
                        verbose_name="Турнир",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_registration_coverages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Покрытие регистрации турнира",
                "verbose_name_plural": "Покрытия регистрации турниров",
                "unique_together": {("tournament", "user")},
            },
        ),
    ]
