# Generated by Django 6.0.1 on 2026-04-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0019_club_tournament_proxy"),
        ("courts", "0013_court_split_surface_fields"),
        ("tournaments", "0044_alter_tournamentallowedcategory_options_and_more"),
        ("users", "0031_player_users_playe_is_bye_fd7aa1_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["status", "-start_date"], name="tournaments_status_9d8850_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["club", "status", "-start_date"],
                name="tournaments_club_id_0a8489_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["registration_deadline"], name="tournaments_registr_c4ffa2_idx"
            ),
        ),
    ]
