# Generated by Django 6.0.1 on 2026-04-24 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sparring",
            "0015_rename_sparring_sp_inviter_4f8a1d_idx_sparring_sp_inviter_001ec2_idx_and_more",
        ),
        ("tournaments", "0045_tournament_tournaments_status_9d8850_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="sparring_team_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Для командного спарринга хранит исходную заявку, к которой относится матч из серии.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="series_matches",
                to="sparring.doublesmatchrequest",
                verbose_name="Командная серия спарринга",
            ),
        ),
    ]
