# Generated by Django 6.0.1 on 2026-07-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0046_match_sparring_team_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentphoto",
            name="caption",
            field=models.CharField(blank=True, max_length=200, verbose_name="Подпись"),
        ),
    ]
