# Generated by Django 6.0.1 on 2026-07-19 16:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0047_tournamentphoto_caption"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="postpayment_deadline_hours",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="Через сколько часов после запуска окна неоплатившие удаляются. При изменении значения сроки (due_at) у активных инвойсов пересчитываются от момента старта окна.",
                verbose_name="Длительность окна постоплаты (часы)",
            ),
        ),
        migrations.CreateModel(
            name="TournamentPostpaymentCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "called_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Время звонка"
                    ),
                ),
                (
                    "called_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournament_postpayment_calls_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто звонил",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postpayment_call_logs",
                        to="tournaments.tournament",
                        verbose_name="Турнир",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_postpayment_call_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Звонок по постоплате",
                "verbose_name_plural": "Звонки по постоплате",
                "unique_together": {("tournament", "user")},
            },
        ),
    ]
