# Generated by Django 6.0.1 on 2026-07-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0048_tournament_postpayment_call_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="allow_postpayment",
            field=models.BooleanField(
                default=False,
                help_text="Разрешить регистрацию без немедленной оплаты вступительного взноса. После дедлайна регистрации участникам без оплаты отправляется ссылка; срок оплаты задаётся полем «Длительность окна постоплаты» ниже.",
                verbose_name="Постоплата",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="postpayment_deadline_hours",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="Сколько часов есть на оплату после старта окна. По умолчанию 12; можно увеличить (например, до 24). При изменении сроки у активных инвойсов пересчитываются от момента старта окна.",
                verbose_name="Длительность окна постоплаты (часы)",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="postpayment_window_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Фактическое время открытия окна (заполняется автоматически). Конец окна = старт + длительность в часах.",
                null=True,
                verbose_name="Старт окна постоплаты",
            ),
        ),
    ]
