# Generated by Django 6.0.1 on 2026-07-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0049_clarify_postpayment_window_help_texts"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentpostpaymentinvoice",
            name="payment_link_resent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Время последней ручной повторной отправки ссылки на оплату.",
                null=True,
                verbose_name="Повторная отправка ссылки",
            ),
        ),
    ]
