# Generated by Django 6.0.1 on 2026-07-25 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0050_invoice_payment_link_resent_at"),
        ("users", "0032_user_email_verified_emailverificationtoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Снят"),
                ),
                (
                    "fancoin_refunded",
                    models.BooleanField(
                        default=False,
                        help_text="True, если при снятии был возврат FT (не было сыгранных матчей).",
                        verbose_name="FT возвращены",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_withdrawals",
                        to="users.player",
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_withdrawals",
                        to="tournaments.tournamentteam",
                        verbose_name="Команда",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="tournaments.tournament",
                        verbose_name="Турнир",
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournament_withdrawals_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто снял",
                    ),
                ),
            ],
            options={
                "verbose_name": "Снятие с турнира",
                "verbose_name_plural": "Снятия с турниров",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("player__isnull", False)),
                        fields=("tournament", "player"),
                        name="uniq_tournament_withdrawal_player",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("team__isnull", False)),
                        fields=("tournament", "team"),
                        name="uniq_tournament_withdrawal_team",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("player__isnull", False), ("team__isnull", True)),
                            models.Q(("player__isnull", True), ("team__isnull", False)),
                            _connector="OR",
                        ),
                        name="tournament_withdrawal_player_xor_team",
                    ),
                ],
            },
        ),
    ]
