# Generated by Django 6.0.1 on 2026-08-11 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0051_tournament_withdrawal"),
        ("users", "0032_user_email_verified_emailverificationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentphoto",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournament_photos",
                to="users.player",
                verbose_name="Загрузил",
            ),
        ),
    ]
