# Generated by Django 6.0.1 on 2026-08-20 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0054_match_walkover_no_show_sides"),
        ("users", "0032_user_email_verified_emailverificationtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentPhotoPromptDismissal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_photo_prompt_dismissals",
                        to="users.player",
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_prompt_dismissals",
                        to="tournaments.tournament",
                        verbose_name="Турнир",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отказ от напоминания о фото",
                "verbose_name_plural": "Отказы от напоминания о фото",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tournament", "player"),
                        name="uniq_tournament_photo_prompt_dismissal",
                    )
                ],
            },
        ),
    ]
