# Generated by Django 6.0.1 on 2026-09-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0057_backfill_geo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Населённый пункт"),
        ),
    ]
