# Generated by Django 6.0.1 on 2026-09-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0059_rename_zone_to_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="completion_notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Заполняется автоматически при первой рассылке после завершения турнира.",
                null=True,
                verbose_name="Когда отправлены письма об итогах",
            ),
        ),
    ]
