# Generated by Django 6.0.1 on 2026-09-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0060_tournament_completion_notified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="min_fill_reached_notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Для режима «Старт после набора»: заполняется при первом достижении минимального состава.",
                null=True,
                verbose_name="Когда отправлено уведомление о наборе минимума",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="start_after_fill",
            field=models.BooleanField(
                default=False,
                help_text="Дата старта и дедлайн регистрации не задаются. При наборе минимума — письмо админу; при наборе максимума — автоматический запуск турнира и формирование сетки.",
                verbose_name="Старт после набора",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="registration_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Не используется при режиме «Старт после набора» (запуск по набору участников).",
                null=True,
                verbose_name="Дедлайн регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Необязательна при режиме «Старт после набора» — дата проставится при автозапуске.",
                null=True,
                verbose_name="Дата начала",
            ),
        ),
    ]
