# Generated by Django 6.0.1 on 2026-09-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0061_start_after_fill"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tournamentphoto",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Фото турнира",
                "verbose_name_plural": "Фото турниров",
            },
        ),
        migrations.AlterField(
            model_name="tournamentphoto",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Не влияет на отображение: в галерее сначала новые фото.",
                verbose_name="Порядок",
            ),
        ),
    ]
