# Generated by Django 6.0.1 on 2026-09-30 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0022_club_admin_assigned_audit"),
        ("core", "0034_rename_zone_to_district"),
        ("courts", "0023_sport_padel"),
        ("tournaments", "0062_tournamentphoto_order_newest_first"),
        ("users", "0035_sport_padel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SportSeasonPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[("tennis", "Теннис"), ("padel", "Падел")],
                        db_index=True,
                        default="padel",
                        max_length=20,
                        verbose_name="Вид спорта",
                    ),
                ),
                (
                    "current_season_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Очки текущего сезона"
                    ),
                ),
                (
                    "season_name",
                    models.CharField(
                        default="", max_length=20, verbose_name="Название сезона"
                    ),
                ),
                (
                    "season_year",
                    models.IntegerField(default=0, verbose_name="Год сезона"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Сезонные очки вида спорта",
                "verbose_name_plural": "Сезонные очки видов спорта",
                "ordering": ["-current_season_points"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="seasonarchive",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="seasonrating",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="match",
            name="sport",
            field=models.CharField(
                choices=[("tennis", "Теннис"), ("padel", "Падел")],
                db_index=True,
                default="tennis",
                help_text="Для турнирного матча совпадает с турниром. От него зависит, какой рейтинг обновлять.",
                max_length=20,
                verbose_name="Вид спорта",
            ),
        ),
        migrations.AddField(
            model_name="seasonarchive",
            name="sport",
            field=models.CharField(
                choices=[("tennis", "Теннис"), ("padel", "Падел")],
                db_index=True,
                default="tennis",
                max_length=20,
                verbose_name="Вид спорта",
            ),
        ),
        migrations.AddField(
            model_name="seasonrating",
            name="sport",
            field=models.CharField(
                choices=[("tennis", "Теннис"), ("padel", "Падел")],
                db_index=True,
                default="tennis",
                max_length=20,
                verbose_name="Вид спорта",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="sport",
            field=models.CharField(
                choices=[("tennis", "Теннис"), ("padel", "Падел")],
                db_index=True,
                default="tennis",
                help_text="Падел проводится парными командами и считает отдельный рейтинг.",
                max_length=20,
                verbose_name="Вид спорта",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seasonarchive",
            unique_together={("player", "season_name", "season_year", "sport")},
        ),
        migrations.AlterUniqueTogether(
            name="seasonrating",
            unique_together={("player", "season", "category", "sport")},
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["sport", "status", "-start_date"],
                name="tournaments_sport_1f6ea4_idx",
            ),
        ),
        migrations.AddField(
            model_name="sportseasonpoints",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sport_season_points",
                to="users.player",
                verbose_name="Игрок",
            ),
        ),
        migrations.AddConstraint(
            model_name="sportseasonpoints",
            constraint=models.UniqueConstraint(
                fields=("player", "sport"), name="tournaments_sport_season_points_uniq"
            ),
        ),
    ]
