# Generated by Django 6.0.1 on 2026-10-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0064_tournament_regulation_extra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seasonrating",
            name="category",
            field=models.CharField(
                choices=[
                    ("novice", "Новичок"),
                    ("amateur", "Любитель"),
                    ("experienced", "Опытный"),
                    ("advanced", "Мастер"),
                    ("professional", "Профессионал"),
                ],
                max_length=20,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="tournamentallowedcategory",
            name="category",
            field=models.CharField(
                choices=[
                    ("novice", "Новичок"),
                    ("amateur", "Любитель"),
                    ("experienced", "Опытный"),
                    ("advanced", "Мастер"),
                    ("professional", "Профессионал"),
                ],
                max_length=20,
                verbose_name="Категория",
            ),
        ),
    ]
