# Generated by Django 6.0.1 on 2026-01-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, upload_to='coaches/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Опыт (лет)')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Специализация')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('city', models.CharField(choices=[('moscow', 'Москва'), ('spb', 'Санкт-Петербург')], default='moscow', max_length=20, verbose_name='Город')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('preferred_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Предпочтительное время')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Запись на тренировку',
                'verbose_name_plural': 'Записи на тренировки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('training_type', models.CharField(choices=[('individual', 'Индивидуальная'), ('group', 'Групповая'), ('mini_group', 'Мини-группа (2-4 чел.)')], default='individual', max_length=20, verbose_name='Тип тренировки')),
                ('skill_level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('all', 'Все уровни')], default='all', max_length=20, verbose_name='Уровень')),
                ('target_category', models.CharField(blank=True, choices=[('futures', 'Futures'), ('base', 'Base'), ('tour', 'Tour'), ('hard', 'Hard'), ('challenger', 'Challenger'), ('masters', 'Masters')], max_length=20, verbose_name='Целевая категория')),
                ('city', models.CharField(choices=[('moscow', 'Москва'), ('spb', 'Санкт-Петербург')], default='moscow', max_length=20, verbose_name='Город')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='Длительность (мин)')),
                ('max_participants', models.PositiveSmallIntegerField(default=1, verbose_name='Макс. участников')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('schedule', models.TextField(blank=True, help_text='Дни и время проведения', verbose_name='Расписание')),
                ('image', models.ImageField(blank=True, upload_to='trainings/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_featured', models.BooleanField(default=False, verbose_name='На главной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='training.coach', verbose_name='Тренер')),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='courts.court', verbose_name='Корт')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
