# Generated by Django 6.0.1 on 2026-01-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_training_target_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='training',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
    ]
