# Generated by Django 6.0.1 on 2026-01-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_training_target_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='max_contact',
            field=models.CharField(blank=True, help_text='Ссылка на профиль в мессенджере MAX', max_length=500, verbose_name='MAX'),
        ),
    ]
