# Generated by Django 6.0.1 on 2026-01-28 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_add_coach_max_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('applicant_name', models.CharField(max_length=200, verbose_name='Контактное лицо')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='Email заявителя')),
                ('applicant_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон заявителя')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('photo', models.ImageField(blank=True, upload_to='coaches/applications/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Опыт (лет)')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Специализация')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('max_contact', models.CharField(blank=True, max_length=500, verbose_name='MAX')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('coach', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='training.coach', verbose_name='Созданный тренер')),
            ],
            options={
                'verbose_name': 'Заявка на тренера',
                'verbose_name_plural': 'Заявки на тренера',
                'ordering': ['-created_at'],
            },
        ),
    ]
