# Generated by Django 6.0.1 on 2026-01-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_enrollment_contact_fields'),
        ('training', '0009_add_coach_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingenrollment',
            name='desired_court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_requests', to='courts.court', verbose_name='Желаемый корт'),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
    ]
