# Generated by Django 6.0.1 on 2026-02-12 17:43

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_coach_user_enrollment_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='photo',
            field=models.ImageField(blank=True, upload_to='coaches/', validators=[config.validators.validate_image_max_2mb], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='coachapplication',
            name='photo',
            field=models.ImageField(blank=True, upload_to='coaches/applications/', validators=[config.validators.validate_image_max_2mb], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='training',
            name='image',
            field=models.ImageField(blank=True, upload_to='trainings/', validators=[config.validators.validate_image_max_2mb], verbose_name='Изображение'),
        ),
    ]
