# Generated by Django 6.0.1 on 2026-02-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0012_alter_coach_photo_alter_coachapplication_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="skill_level",
            field=models.CharField(
                choices=[
                    ("novice", "Новичок"),
                    ("amateur", "Любитель"),
                    ("experienced", "Опытный"),
                    ("advanced", "Мастерс"),
                    ("professional", "Профессионал"),
                ],
                default="amateur",
                max_length=20,
                verbose_name="Уровень",
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="target_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("novice", "Новичок"),
                    ("amateur", "Любитель"),
                    ("experienced", "Опытный"),
                    ("advanced", "Мастерс"),
                    ("professional", "Профессионал"),
                ],
                max_length=20,
                verbose_name="Целевой уровень (NTRP)",
            ),
        ),
    ]
