# Generated by Django 6.0.1 on 2026-02-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0013_alter_training_skill_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="target_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("novice", "Новичок"),
                    ("amateur", "Любитель"),
                    ("experienced", "Опытный"),
                    ("advanced", "Мастерс"),
                    ("professional", "Профессионал"),
                ],
                max_length=20,
                verbose_name="Целевой уровень силы",
            ),
        ),
    ]
