# Generated by Django 6.0.1 on 2026-02-26 11:25

from django.db import migrations, models


def migrate_court_to_courts(apps, schema_editor):
    """Перенос единственного корта в связь M2M «корты»."""
    Training = apps.get_model("training", "Training")
    for training in Training.objects.filter(court_id__isnull=False):
        training.courts.add(training.court_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0008_court_extra_fields_and_rental_price_range"),
        ("training", "0014_alter_training_target_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="courts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Один тренер может проводить тренировки на разных площадках.",
                related_name="trainings",
                to="courts.court",
                verbose_name="Корты",
            ),
        ),
        migrations.RunPython(migrate_court_to_courts, noop),
        migrations.RemoveField(
            model_name="training",
            name="court",
        ),
    ]
