# Generated by Django 6.0.1 on 2026-03-25 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0018_training_court_has_extra_fee"),
        ("users", "0027_ntrp_test_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingenrollment",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_enrollments",
                to="users.player",
                verbose_name="Игрок",
            ),
        ),
    ]
