# Generated by Django 6.0.1 on 2026-04-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0019_alter_trainingenrollment_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="max_contact",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на профиль в мессенджере MAX или номер телефона, привязанный к MAX.",
                max_length=500,
                verbose_name="MAX",
            ),
        ),
    ]
