# Generated by Django 6.0.1 on 2026-09-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0020_alter_coach_max_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Населённый пункт"),
        ),
        migrations.AlterField(
            model_name="coachapplication",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Населённый пункт"),
        ),
        migrations.AlterField(
            model_name="training",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Населённый пункт"),
        ),
    ]
