# Generated by Django 6.0.1 on 2026-10-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0022_sport_padel"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="sport",
            field=models.CharField(
                choices=[
                    ("tennis", "Теннис"),
                    ("padel", "Падел"),
                    ("both", "Теннис и падел"),
                ],
                db_index=True,
                default="tennis",
                max_length=20,
                verbose_name="Вид спорта",
            ),
        ),
        migrations.AddField(
            model_name="coachapplication",
            name="sport",
            field=models.CharField(
                choices=[
                    ("tennis", "Теннис"),
                    ("padel", "Падел"),
                    ("both", "Теннис и падел"),
                ],
                db_index=True,
                default="tennis",
                max_length=20,
                verbose_name="Вид спорта",
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="sport",
            field=models.CharField(
                choices=[
                    ("tennis", "Теннис"),
                    ("padel", "Падел"),
                    ("both", "Теннис и падел"),
                ],
                db_index=True,
                default="tennis",
                max_length=20,
                verbose_name="Вид спорта",
            ),
        ),
    ]
