# Generated by Django 6.0.1 on 2026-01-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('address', 'Адрес'), ('phone', 'Телефон'), ('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('vk', 'VK'), ('website', 'Сайт'), ('work_hours', 'Режим работы'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип')),
                ('label', models.CharField(blank=True, help_text='Например: «Поддержка», «Офис». Если пусто — используется тип.', max_length=100, verbose_name='Подпись (опционально)')),
                ('value', models.CharField(help_text='Телефон, адрес, @username, email и т.д.', max_length=500, verbose_name='Значение')),
                ('url', models.URLField(blank=True, help_text='Для мессенджеров: t.me/xxx, wa.me/xxx. Для email: mailto:...', verbose_name='Ссылка (опционально)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['order', 'id'],
            },
        ),
    ]
