# Generated by Django 6.0.1 on 2026-01-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_add_contact_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(blank=True, help_text='Произвольный текст (приветствие, описание и т.д.). Поддерживается Markdown.', verbose_name='Текст перед контактами')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Страница контактов',
                'verbose_name_plural': 'Страница контактов',
            },
        ),
        migrations.AlterField(
            model_name='contactitem',
            name='item_type',
            field=models.CharField(choices=[('address', 'Адрес'), ('phone', 'Телефон'), ('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('max', 'MAX'), ('vk', 'VK'), ('website', 'Сайт'), ('work_hours', 'Режим работы'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип'),
        ),
    ]
