# Generated by Django 6.0.1 on 2026-01-30 11:09

import django.db.models.deletion
from django.db import migrations, models


def assign_contact_items_to_page(apps, schema_editor):
    """Привязать существующие ContactItem к ContactPage."""
    ContactPage = apps.get_model("content", "ContactPage")
    ContactItem = apps.get_model("content", "ContactItem")
    page = ContactPage.objects.first()
    if page:
        ContactItem.objects.filter(contact_page__isnull=True).update(contact_page=page)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_add_contact_page_and_max'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='contactitem',
            name='contact_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_items', to='content.contactpage', verbose_name='Страница контактов'),
        ),
        migrations.RunPython(assign_contact_items_to_page, noop),
    ]
