# Generated by Django 6.0.1 on 2026-02-09 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import config.validators


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_add_video_page"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StringerCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Наименование")),
                ("address", models.CharField(max_length=300, verbose_name="Адрес")),
                (
                    "contacts",
                    models.TextField(
                        help_text="Телефон, email, сайт, социальные сети и т.д. Можно использовать несколько строк.",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True,
                        help_text="Например: 'от 500 руб.', '500-1000 руб.' и т.д.",
                        max_length=200,
                        verbose_name="Стоимость",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активна (показывать)"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Компания стрингеров",
                "verbose_name_plural": "Компании стрингеров",
                "ordering": ["order", "name"],
            },
            bases=(config.validators.CompressImageFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StringerPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Стрингеры",
                        max_length=200,
                        verbose_name="Заголовок страницы",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Текст, который отображается вверху страницы перед списком компаний.",
                        verbose_name="Описание страницы",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Включить страницу"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Страница «Стрингеры»",
                "verbose_name_plural": "Страница «Стрингеры»",
            },
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="about/",
                validators=[config.validators.validate_image_max_2mb],
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                upload_to="galleries/covers/",
                validators=[config.validators.validate_image_max_2mb],
                verbose_name="Обложка",
            ),
        ),
        migrations.AlterField(
            model_name="livestream",
            name="url",
            field=models.URLField(
                help_text="YouTube: любая ссылка (youtube.com/watch?v=... или youtu.be/...). VK: используйте формат vk.com/video-XXXXX_YYYYY. RuTube: любая ссылка на видео.",
                verbose_name="Ссылка на трансляцию",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="news/",
                validators=[config.validators.validate_image_max_2mb],
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="newsphoto",
            name="image",
            field=models.ImageField(
                upload_to="news/gallery/",
                validators=[config.validators.validate_image_max_2mb],
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                upload_to="galleries/photos/",
                validators=[config.validators.validate_image_max_2mb],
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="rulessection",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Код раздела"),
        ),
        migrations.AlterField(
            model_name="video",
            name="url",
            field=models.URLField(
                help_text="YouTube: любая ссылка (youtube.com/watch?v=... или youtu.be/...). VK: используйте формат vk.com/video-XXXXX_YYYYY. RuTube: любая ссылка на видео.",
                verbose_name="Ссылка на видео",
            ),
        ),
        migrations.CreateModel(
            name="StringerCompanyPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="stringers/photos/",
                        validators=[config.validators.validate_image_max_2mb],
                        verbose_name="Фото",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подпись"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="content.stringercompany",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото компании",
                "verbose_name_plural": "Фото компаний",
                "ordering": ["order", "-created_at"],
            },
            bases=(config.validators.CompressImageFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StringerCompanyRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="Оценка от 1 до 5",
                        verbose_name="Оценка",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="content.stringercompany",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stringer_ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка компании",
                "verbose_name_plural": "Оценки компаний",
                "ordering": ["-created_at"],
                "unique_together": {("company", "user")},
            },
        ),
    ]
