# Generated by Django 6.0.1 on 2026-02-09 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_add_stringer_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="stringercompany",
            name="stringer_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to="content.stringerpage",
                verbose_name="Страница стрингеров",
            ),
        ),
    ]
