# Generated by Django 6.0.1 on 2026-02-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_supportmessage_admin_telegram_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertelegramlink',
            name='user_bot_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Заполняется только после /start в чате с ботом уведомлений (кнопка «Подключить» на профиле).', null=True, unique=True, verbose_name='Chat ID для пользовательского бота'),
        ),
        migrations.AlterField(
            model_name='usertelegramlink',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Используется ботом поддержки для ответов пользователю.', null=True, unique=True, verbose_name='Telegram chat_id (бот поддержки)'),
        ),
    ]
