# Generated by Django 6.0.1 on 2026-02-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_guest_fields_to_support_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportmessage",
            name="guest_binding_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Токен для привязки Telegram бота гостю (t.me/bot?start=TOKEN)",
                max_length=64,
                unique=True,
                verbose_name="Токен привязки для гостя",
            ),
        ),
        migrations.AddField(
            model_name="supportmessage",
            name="guest_telegram_chat_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Chat ID гостя в Telegram (заполняется после привязки бота)",
                null=True,
                verbose_name="Telegram chat_id гостя",
            ),
        ),
        migrations.AddField(
            model_name="supportmessage",
            name="guest_telegram_username",
            field=models.CharField(
                blank=True,
                help_text="Telegram username незарегистрированного пользователя (без @)",
                max_length=100,
                verbose_name="Telegram username гостя",
            ),
        ),
    ]
