# Generated by Django 6.0.1 on 2026-02-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_guest_telegram_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSocialLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_url",
                    models.URLField(
                        blank=True,
                        help_text="Оставьте пустым, чтобы использовать значение из настроек (TELEGRAM_PUBLIC_COMMUNITY_URL).",
                        max_length=500,
                        verbose_name="Ссылка на Telegram",
                    ),
                ),
                (
                    "vk_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Ссылка на ВКонтакте"
                    ),
                ),
            ],
            options={
                "verbose_name": "соцсети в футере",
                "verbose_name_plural": "Соцсети",
            },
        ),
    ]
