# Generated by Django 6.0.1 on 2026-02-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_populate_footer_social_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Telegram, ВКонтакте. Используется в подсказке (aria-label).",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="Ссылка")),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        help_text="Загрузите SVG-файл иконки. Либо укажите путь в поле «Путь к иконке».",
                        upload_to="footer_social/",
                        verbose_name="Иконка (SVG)",
                    ),
                ),
                (
                    "icon_path",
                    models.CharField(
                        blank=True,
                        help_text="Если иконка не загружена: путь относительно static, например images/VK.svg.",
                        max_length=200,
                        verbose_name="Путь к иконке в static",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "ссылка на соцсеть",
                "verbose_name_plural": "Соцсети",
                "ordering": ["order", "id"],
            },
        ),
    ]
