# Generated by Django 6.0.1 on 2026-03-06 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_city_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportmessage",
            name="admin_telegram_message_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Сохраняем первый успешный message_id для совместимости; у каждого админа свой message_id.",
                null=True,
                verbose_name="ID сообщения в Telegram (админу)",
            ),
        ),
        migrations.CreateModel(
            name="SupportMessageAdminDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_chat_id",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        verbose_name="Chat ID админа в Telegram",
                    ),
                ),
                (
                    "admin_telegram_message_id",
                    models.BigIntegerField(
                        db_index=True, verbose_name="ID сообщения в чате админа"
                    ),
                ),
                (
                    "support_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_deliveries",
                        to="core.supportmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "доставка сообщения админу",
                "verbose_name_plural": "доставки сообщений админам",
                "unique_together": {("admin_chat_id", "admin_telegram_message_id")},
            },
        ),
    ]
