# Generated by Django 6.0.1 on 2026-03-10 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_support_admin_delivery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalAcceptanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_slug",
                    models.CharField(
                        choices=[
                            ("personal-data", "Согласие на обработку ПДн"),
                            ("privacy", "Политика конфиденциальности"),
                            ("offer", "Публичная оферта"),
                            ("terms", "Пользовательское соглашение"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Документ",
                    ),
                ),
                (
                    "document_version",
                    models.CharField(
                        db_index=True,
                        default="unknown",
                        max_length=64,
                        verbose_name="Версия документа",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="site",
                        help_text="Например: registration, payment, profile.",
                        max_length=64,
                        verbose_name="Источник акцепта",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-адрес"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User-Agent"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Дополнительные данные"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время фиксации"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_acceptances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "фиксация согласия с документом",
                "verbose_name_plural": "фиксации согласий с документами",
                "ordering": ["-accepted_at"],
            },
        ),
    ]
