# Generated by Django 6.0.1 on 2026-03-25 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0017_club_legal_and_user_consent"),
        ("core", "0015_legalacceptancelog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("platform_offer", "Публичная оферта платформы"),
                            ("privacy_policy", "Политика конфиденциальности"),
                            (
                                "club_organizer_rules",
                                "Правила для организаторов клубов",
                            ),
                            ("club_offer", "Оферта клуба"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="Тип согласия",
                    ),
                ),
                (
                    "document_version",
                    models.CharField(max_length=64, verbose_name="Версия документа"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Принято"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-адрес"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="User-Agent",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        help_text="Только для согласия с офертой клуба",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_consents",
                        to="clubs.club",
                        verbose_name="Клуб",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_consents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "согласие пользователя",
                "verbose_name_plural": "согласия пользователей",
                "ordering": ["-accepted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("club__isnull", True)),
                        fields=("user", "consent_type", "document_version"),
                        name="uniq_userconsent_platform",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("club__isnull", False)),
                        fields=("user", "consent_type", "club", "document_version"),
                        name="uniq_userconsent_club",
                    ),
                ],
            },
        ),
    ]
