# Generated by Django 6.0.1 on 2026-04-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_support_threads_refactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportthread",
            name="guest_email",
            field=models.EmailField(
                blank=True,
                help_text="Email гостя, если диалог создан без авторизации.",
                max_length=254,
                verbose_name="Email гостя",
            ),
        ),
        migrations.AlterField(
            model_name="supportthread",
            name="guest_name",
            field=models.CharField(
                blank=True,
                help_text="Имя гостя, если диалог создан без авторизации.",
                max_length=200,
                verbose_name="Имя гостя",
            ),
        ),
        migrations.AlterField(
            model_name="supportthread",
            name="guest_session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Используется для доступа гостя к своему диалогу из виджета.",
                max_length=64,
                verbose_name="Ключ сессии гостя",
            ),
        ),
    ]
