# Generated by Django 6.0.1 on 2026-05-29 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_city_coordinates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformActivityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("registration", "Регистрация"),
                            ("payment_subscription", "Оплата подписки"),
                            ("payment_club_plan", "Оплата тарифа клуба"),
                            ("payment_club_fee", "Оплата членского взноса"),
                            ("payment_tournament", "Оплата турнира"),
                            ("payment_donation", "Донат"),
                            ("tournament_registered", "Регистрация на турнир"),
                            ("match_result_proposed", "Внесён результат матча"),
                            ("match_result_confirmed", "Подтверждён результат матча"),
                            ("sparring_created", "Создан спарринг"),
                            ("sparring_applied", "Отклик на спарринг"),
                            ("sparring_approved", "Одобрен отклик на спарринг"),
                            ("sparring_invited", "Приглашение на спарринг"),
                            ("doubles_created", "Создан парный спарринг"),
                            ("doubles_join_requested", "Заявка в парный спарринг"),
                            (
                                "doubles_join_approved",
                                "Одобрена заявка в парный спарринг",
                            ),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="Тип события",
                    ),
                ),
                (
                    "actor_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Снимок ФИО/email действующего лица, сохраняется навсегда.",
                        max_length=255,
                        verbose_name="Имя на момент события",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Описание действия"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Заполняется только для событий-оплат.",
                        max_digits=10,
                        null=True,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default="RUB", max_length=8, verbose_name="Валюта"
                    ),
                ),
                (
                    "target_url",
                    models.CharField(
                        blank=True,
                        help_text="Относительный URL связанного объекта (матч, турнир и т.д.).",
                        max_length=500,
                        verbose_name="Ссылка на объект",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Дополнительные данные"
                    ),
                ),
                (
                    "dedupe_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Стабильный ключ источника события для защиты от дубликатов.",
                        max_length=120,
                        verbose_name="Ключ дедупликации",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Когда произошло",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Кто совершил действие. NULL — системное событие или удалённый пользователь.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_activity_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "событие активности",
                "verbose_name_plural": "лента активности платформы",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="core_platfo_event_t_f831f3_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="core_platfo_actor_i_8a409a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dedupe_key__gt", "")),
                        fields=("dedupe_key",),
                        name="uniq_activity_dedupe_key",
                    )
                ],
            },
        ),
    ]
