# Generated by Django 6.0.1 on 2026-05-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_platformactivityevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformactivityevent",
            name="actor_role",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Снимок роли действующего лица: Игрок, Тренер, Админ и т.д.",
                max_length=32,
                verbose_name="Статус пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="platformactivityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("registration", "Регистрация"),
                    ("payment_subscription", "Оплата подписки"),
                    ("payment_club_plan", "Оплата тарифа клуба"),
                    ("payment_club_fee", "Оплата членского взноса"),
                    ("payment_tournament", "Оплата турнира"),
                    ("payment_donation", "Донат"),
                    ("tournament_registered", "Регистрация на турнир"),
                    ("match_result_proposed", "Внесён результат матча"),
                    ("match_result_confirmed", "Подтверждён результат матча"),
                    ("match_result_rejected", "Отклонён результат матча"),
                    ("sparring_created", "Создан спарринг"),
                    ("sparring_applied", "Отклик на спарринг"),
                    ("sparring_approved", "Одобрен отклик на спарринг"),
                    ("sparring_rejected", "Отклонён отклик на спарринг"),
                    ("sparring_invited", "Приглашение на спарринг"),
                    ("doubles_created", "Создан парный спарринг"),
                    ("doubles_join_requested", "Заявка в парный спарринг"),
                    ("doubles_join_approved", "Одобрена заявка в парный спарринг"),
                    ("doubles_join_rejected", "Отклонена заявка в парный спарринг"),
                    ("club_join_requested", "Заявка в клуб"),
                    ("club_joined", "Вступление в клуб"),
                    ("club_join_rejected", "Отклонена заявка в клуб"),
                    ("coach_application", "Заявка на тренера"),
                    ("training_published", "Опубликована тренировка"),
                    ("training_enrolled", "Запись на тренировку"),
                    ("comment_added", "Комментарий"),
                    ("subscription_cancelled", "Отмена подписки"),
                    ("fancoin_charge", "Списание FAN-коинов"),
                    ("fancoin_refund", "Возврат FAN-коинов"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="Тип события",
            ),
        ),
    ]
