# Generated by Django 6.0.1 on 2026-05-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_platformdashboardseen"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformdashboardseen",
            name="last_seen_event_id",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="События с большим id считаются непросмотренными.",
                verbose_name="ID последнего просмотренного события",
            ),
        ),
    ]
