# Generated by Django 6.0.1 on 2026-06-05 18:52

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("core", "0024_platformdashboardseen_last_seen_event_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[],
            options={
                "verbose_name": "Действие в админке",
                "verbose_name_plural": "Журнал действий",
                "ordering": ("-action_time", "-pk"),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin.logentry",),
            managers=[
                ("objects", django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
