# Generated by Django 6.0.1 on 2026-07-20 08:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_admin_action_log_proxy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboundEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "to_email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="Кому"
                    ),
                ),
                (
                    "from_email",
                    models.CharField(
                        blank=True, max_length=254, verbose_name="От кого"
                    ),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=998, verbose_name="Тема"),
                ),
                ("body_text", models.TextField(blank=True, verbose_name="Текст")),
                ("body_html", models.TextField(blank=True, verbose_name="HTML")),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Отправлено"), ("failed", "Ошибка")],
                        db_index=True,
                        default="sent",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "sent_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Отправлено",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_emails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Электронное письмо",
                "verbose_name_plural": "Электронные письма",
                "ordering": ("-sent_at", "-id"),
            },
        ),
    ]
