# Generated by Django 6.0.1 on 2026-07-24 10:53

from django.db import migrations, models


def classify_existing_emails(apps, schema_editor):
    """Проставить раздел существующим письмам по теме."""
    OutboundEmail = apps.get_model("core", "OutboundEmail")
    from apps.core.email_categories import classify_outbound_email

    for row in OutboundEmail.objects.all().iterator(chunk_size=500):
        category = classify_outbound_email(subject=row.subject or "")
        if row.category != category:
            row.category = category
            row.save(update_fields=["category"])


def noop_reverse(apps, schema_editor):
    """Откат классификации не требуется."""
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_outbound_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubsOutboundEmail",
            fields=[],
            options={
                "verbose_name": "Клубное письмо",
                "verbose_name_plural": "Клубы",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.outboundemail",),
        ),
        migrations.CreateModel(
            name="NewTournamentOutboundEmail",
            fields=[],
            options={
                "verbose_name": "Письмо о новом турнире",
                "verbose_name_plural": "Новые турниры",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.outboundemail",),
        ),
        migrations.CreateModel(
            name="OtherOutboundEmail",
            fields=[],
            options={
                "verbose_name": "Прочее письмо",
                "verbose_name_plural": "Прочие",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.outboundemail",),
        ),
        migrations.CreateModel(
            name="RegistrationOutboundEmail",
            fields=[],
            options={
                "verbose_name": "Письмо регистрации",
                "verbose_name_plural": "Регистрация и подтверждение почты",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.outboundemail",),
        ),
        migrations.CreateModel(
            name="SecurityOutboundEmail",
            fields=[],
            options={
                "verbose_name": "Письмо безопасности",
                "verbose_name_plural": "Безопасность",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.outboundemail",),
        ),
        migrations.CreateModel(
            name="SubscriptionOutboundEmail",
            fields=[],
            options={
                "verbose_name": "Письмо подписки/платежа",
                "verbose_name_plural": "Подписки и платежи",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.outboundemail",),
        ),
        migrations.CreateModel(
            name="SupportOutboundEmail",
            fields=[],
            options={
                "verbose_name": "Письмо поддержки",
                "verbose_name_plural": "Поддержка",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.outboundemail",),
        ),
        migrations.CreateModel(
            name="TournamentOutboundEmail",
            fields=[],
            options={
                "verbose_name": "Письмо по турниру",
                "verbose_name_plural": "Турниры",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.outboundemail",),
        ),
        migrations.AlterModelOptions(
            name="outboundemail",
            options={
                "ordering": ("-sent_at", "-id"),
                "verbose_name": "Электронное письмо",
                "verbose_name_plural": "Все письма",
            },
        ),
        migrations.AddField(
            model_name="outboundemail",
            name="category",
            field=models.CharField(
                choices=[
                    ("registration", "Регистрация и подтверждение почты"),
                    ("new_tournament", "Новые турниры"),
                    ("tournament", "Турниры"),
                    ("subscription", "Подписки и платежи"),
                    ("security", "Безопасность"),
                    ("clubs", "Клубы"),
                    ("support", "Поддержка"),
                    ("other", "Прочие"),
                ],
                db_index=True,
                default="other",
                max_length=32,
                verbose_name="Раздел",
            ),
        ),
        migrations.RunPython(classify_existing_emails, noop_reverse),
    ]
