# Generated by Django 6.0.1 on 2026-08-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_platformactivityevent_admin_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("moscow", "Москва"),
                            ("moscow_oblast", "Московская область"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Регион",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Юго-Восток, Раменское.",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Часть адреса страницы: yugo-vostok, ramenskoe.",
                        max_length=100,
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "aliases",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="По одному в строке. Используются для распознавания зоны в названиях турниров, например «ЮВАО» или «юго-восток».",
                        verbose_name="Варианты написания",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Определяет позицию в фильтрах и меню.",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "is_advertised",
                    models.BooleanField(
                        default=False,
                        help_text="Для площадки создаётся отдельная страница под рекламный трафик.",
                        verbose_name="Рекламное направление",
                    ),
                ),
            ],
            options={
                "verbose_name": "зона / город",
                "verbose_name_plural": "Зоны Москвы и города области",
                "ordering": ["region", "sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("region", "name"), name="uniq_geoarea_region_name"
                    )
                ],
            },
        ),
    ]
