# Generated by Django 6.0.1 on 2026-09-03 08:08

from django.db import migrations, models


def seed_non_city_localities(apps, schema_editor):
    """Добавить типичные не-городские пункты для автодополнения без Yandex."""
    City = apps.get_model("core", "City")
    seeds = [
        {
            "name": "Листвянка",
            "settlement_type": "pgt",
            "region": "Ивановская область",
            "lat": None,
            "lng": None,
        },
        {
            "name": "Константиново",
            "settlement_type": "selo",
            "region": "Рязанская область",
            "lat": 54.859,
            "lng": 39.759,
        },
        {
            "name": "Кимжа",
            "settlement_type": "derevnya",
            "region": "Архангельская область",
            "lat": 65.569,
            "lng": 44.607,
        },
        {
            "name": "Старочеркасская",
            "settlement_type": "stanitsa",
            "region": "Ростовская область",
            "lat": 47.24,
            "lng": 40.042,
        },
        {
            "name": "Гуниб",
            "settlement_type": "aul",
            "region": "Республика Дагестан",
            "lat": 42.388,
            "lng": 46.962,
        },
        {
            "name": "Чох",
            "settlement_type": "aul",
            "region": "Республика Дагестан",
            "lat": 42.385,
            "lng": 47.032,
        },
    ]
    for row in seeds:
        City.objects.get_or_create(
            name=row["name"],
            region=row["region"],
            settlement_type=row["settlement_type"],
            defaults={"lat": row["lat"], "lng": row["lng"]},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_seed_geo_areas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["name"],
                "verbose_name": "населённый пункт",
                "verbose_name_plural": "населённые пункты",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="region",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Субъект РФ, например: Архангельская область.",
                max_length=100,
                verbose_name="Регион",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="settlement_type",
            field=models.CharField(
                choices=[
                    ("city", "город"),
                    ("pgt", "пгт"),
                    ("poselok", "посёлок"),
                    ("selo", "село"),
                    ("derevnya", "деревня"),
                    ("stanitsa", "станица"),
                    ("khutor", "хутор"),
                    ("aul", "аул"),
                    ("other", "населённый пункт"),
                ],
                db_index=True,
                default="city",
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="lat",
            field=models.FloatField(
                blank=True,
                help_text="Широта населённого пункта для отображения на карте.",
                null=True,
                verbose_name="Широта",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="lng",
            field=models.FloatField(
                blank=True,
                help_text="Долгота населённого пункта для отображения на карте.",
                null=True,
                verbose_name="Долгота",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Название"
            ),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                fields=("name", "region", "settlement_type"),
                name="core_city_name_region_type_uniq",
            ),
        ),
        migrations.RunPython(seed_non_city_localities, migrations.RunPython.noop),
    ]
