# Generated by Django 6.0.1 on 2026-09-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_moscow_cardinal_districts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geoarea",
            options={
                "ordering": ["region", "sort_order", "name"],
                "verbose_name": "район / город",
                "verbose_name_plural": "Районы Москвы и города области",
            },
        ),
        migrations.AlterField(
            model_name="geoarea",
            name="aliases",
            field=models.TextField(
                blank=True,
                default="",
                help_text="По одному в строке. Используются для распознавания района в названиях турниров, например «ЮВАО» или «юго-восток».",
                verbose_name="Варианты написания",
            ),
        ),
        migrations.AlterField(
            model_name="geoarea",
            name="name",
            field=models.CharField(
                help_text="Например: Юг, Раменское.",
                max_length=100,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="geoarea",
            name="slug",
            field=models.SlugField(
                help_text="Часть адреса страницы: yug, ramenskoe.",
                max_length=100,
                unique=True,
                verbose_name="Слаг",
            ),
        ),
    ]
