# Generated by Django 6.0.1 on 2026-01-26 17:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond')], max_length=50, unique=True, verbose_name='Название тарифа')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость (руб)')),
                ('max_tournaments', models.PositiveIntegerField(default=0, help_text='0 = без ограничений, или конкретное число', verbose_name='Максимум турниров в месяц')),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Неограниченные регистрации')),
                ('one_day_tournament_discount', models.PositiveIntegerField(default=0, help_text='Процент скидки (0-100)', verbose_name='Скидка на однодневные турниры (%)')),
                ('can_see_stats', models.BooleanField(default=True, verbose_name='Видеть статистику')),
                ('can_read_comments', models.BooleanField(default=True, verbose_name='Читать комментарии')),
                ('can_write_comments', models.BooleanField(default=False, verbose_name='Писать комментарии')),
                ('can_rate_opponents', models.BooleanField(default=False, verbose_name='Оценивать соперников')),
                ('has_private_chat', models.BooleanField(default=False, verbose_name='Доступ в закрытый чат')),
                ('has_sparring', models.BooleanField(default=False, verbose_name='Доступ к спаррингам')),
                ('has_admin_support', models.BooleanField(default=False, verbose_name='Поддержка администратора')),
                ('has_badge', models.BooleanField(default=False, verbose_name='Особый значок')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('tournaments_registered_count', models.PositiveIntegerField(default=0, verbose_name='Использовано регистраций в этом месяце')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptiontier', verbose_name='Тариф')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка пользователя',
                'verbose_name_plural': 'Подписки пользователей',
            },
        ),
    ]
