# Generated by Django migration

from django.db import migrations


def set_has_sparring(apps, schema_editor):
    SubscriptionTier = apps.get_model("subscriptions", "SubscriptionTier")
    SubscriptionTier.objects.filter(name__in=("silver", "gold", "diamond")).update(
        has_sparring=True
    )


def unset_has_sparring(apps, schema_editor):
    SubscriptionTier = apps.get_model("subscriptions", "SubscriptionTier")
    SubscriptionTier.objects.filter(name__in=("silver", "gold", "diamond")).update(
        has_sparring=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(set_has_sparring, unset_has_sparring),
    ]
