# Generated by Django 6.0.1 on 2026-02-10 13:27

from django.db import migrations


def set_diamond_max_tournaments_to_100(apps, schema_editor):
    """Установить max_tournaments = 100 для DIAMOND тарифа."""
    SubscriptionTier = apps.get_model('subscriptions', 'SubscriptionTier')
    diamond_tier = SubscriptionTier.objects.filter(name='diamond').first()
    if diamond_tier:
        diamond_tier.max_tournaments = 100
        diamond_tier.save(update_fields=['max_tournaments'])


def reverse_set_diamond_max_tournaments(apps, schema_editor):
    """Обратная операция: вернуть значение по умолчанию (0)."""
    SubscriptionTier = apps.get_model('subscriptions', 'SubscriptionTier')
    diamond_tier = SubscriptionTier.objects.filter(name='diamond').first()
    if diamond_tier:
        diamond_tier.max_tournaments = 0
        diamond_tier.save(update_fields=['max_tournaments'])


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_set_has_sparring_for_paid_tiers'),
    ]

    operations = [
        migrations.RunPython(
            set_diamond_max_tournaments_to_100,
            reverse_set_diamond_max_tournaments,
        ),
    ]
