# Generated by Django 6.0.1 on 2026-02-10 13:27

from django.db import migrations


def fix_tier_settings(apps, schema_editor):
    """
    Исправить настройки тарифов:
    - FREE: is_unlimited=False, max_tournaments=0 (нет регистраций)
    - DIAMOND: max_tournaments=100 (условный безлимит)
    """
    SubscriptionTier = apps.get_model("subscriptions", "SubscriptionTier")

    free_tier = SubscriptionTier.objects.filter(name="free").first()
    if free_tier:
        free_tier.is_unlimited = False
        free_tier.max_tournaments = 0
        free_tier.save(update_fields=["is_unlimited", "max_tournaments"])

    diamond_tier = SubscriptionTier.objects.filter(name="diamond").first()
    if diamond_tier:
        diamond_tier.max_tournaments = 100
        diamond_tier.save(update_fields=["max_tournaments"])


def reverse_fix_tier_settings(apps, schema_editor):
    """Обратная операция."""
    SubscriptionTier = apps.get_model("subscriptions", "SubscriptionTier")

    free_tier = SubscriptionTier.objects.filter(name="free").first()
    if free_tier:
        free_tier.is_unlimited = True
        free_tier.max_tournaments = 0
        free_tier.save(update_fields=["is_unlimited", "max_tournaments"])

    diamond_tier = SubscriptionTier.objects.filter(name="diamond").first()
    if diamond_tier:
        diamond_tier.max_tournaments = 0
        diamond_tier.save(update_fields=["max_tournaments"])


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_set_has_sparring_for_paid_tiers"),
    ]

    operations = [
        migrations.RunPython(
            fix_tier_settings,
            reverse_fix_tier_settings,
        ),
    ]
