# Generated by Django 6.0.1 on 2026-02-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_regionaltierprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontier",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Если указана — на странице тарифов показывается перечёркнутой, рядом актуальная цена (акция).",
                max_digits=10,
                null=True,
                verbose_name="Цена до скидки (руб)",
            ),
        ),
    ]
