# Generated by Django 6.0.1 on 2026-02-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_add_original_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontier",
            name="original_price_ends_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата и время, после которых перечёркнутая цена не показывается. Пусто — акция без срока.",
                null=True,
                verbose_name="Акционная цена действует до",
            ),
        ),
    ]
