# Generated by Django 6.0.1 on 2026-02-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_add_original_price_ends_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="regionaltierprice",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Перечёркнутая цена для этого региона. Пусто — использовать из тарифа.",
                max_digits=10,
                null=True,
                verbose_name="Цена до скидки (руб)",
            ),
        ),
        migrations.AddField(
            model_name="regionaltierprice",
            name="original_price_ends_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Пусто — использовать срок из тарифа.",
                null=True,
                verbose_name="Акция действует до",
            ),
        ),
    ]
