# Generated by Django 6.0.1 on 2026-02-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_regional_tier_promo_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontier",
            name="first_subscription_one_ruble",
            field=models.BooleanField(
                default=False,
                help_text="Если включено: игрок, который ни разу не покупал подписку, может купить этот тариф за 1 ₽. Все последующие покупки — по обычной цене.",
                verbose_name="Первая подписка за 1 ₽",
            ),
        ),
    ]
