# Generated by Django 6.0.1 on 2026-02-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_first_subscription_one_ruble"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="purchase_city",
            field=models.CharField(
                blank=True,
                help_text="Нормализованное значение города на момент оплаты подписки (moscow / иное). Не менять вручную.",
                max_length=100,
                verbose_name="Город при покупке",
            ),
        ),
    ]
