# Generated by Django 6.0.1 on 2026-03-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0010_add_purchase_city"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptiontier",
            options={
                "ordering": ["sort_order", "price", "id"],
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифы",
            },
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Отображаемое название тарифа в интерфейсе. Если оставить пустым, будет использовано системное название или код.",
                max_length=100,
                verbose_name="Название тарифа на сайте",
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="is_visible",
            field=models.BooleanField(
                default=True, verbose_name="Показывать тариф на сайте"
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок отображения"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptiontier",
            name="name",
            field=models.SlugField(
                help_text="Внутренний код тарифа. Для системных тарифов используйте free, silver, gold или diamond.",
                unique=True,
                verbose_name="Код тарифа",
            ),
        ),
    ]
