# Generated by Django 6.0.1 on 2026-03-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0011_alter_subscriptiontier_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontier",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="На сколько дней активируется или продлевается подписка по этому тарифу.",
                verbose_name="Срок действия (дней)",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptiontier",
            name="name",
            field=models.SlugField(
                blank=True,
                help_text="Внутренний код тарифа. Для новых тарифов можно оставить пустым — он сгенерируется из названия. Для системных тарифов используйте free, silver, gold или diamond.",
                unique=True,
                verbose_name="Код тарифа",
            ),
        ),
    ]
