# Generated by Django 6.0.1 on 2026-03-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0012_subscriptiontier_duration_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontier",
            name="is_popular",
            field=models.BooleanField(
                default=False,
                help_text="Если включено, на карточке тарифа будет показан бейдж «Популярный».",
                verbose_name="Популярный тариф",
            ),
        ),
    ]
