# Generated by Django 6.0.1 on 2026-03-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0014_add_card_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptiontier",
            name="card_theme",
            field=models.CharField(
                choices=[
                    ("none", "Без темы"),
                    ("bronze", "Бронза"),
                    ("silver_theme", "Серебро"),
                    ("gold_theme", "Золото"),
                    ("platinum_theme", "Платина"),
                    ("diamond_theme", "Бриллиант"),
                ],
                default="none",
                help_text="Металлический стиль карточки тарифа на странице подписок.",
                max_length=20,
                verbose_name="Тема оформления карточки",
            ),
        ),
    ]
