# Generated by Django 6.0.1 on 2026-04-24 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def multiply_fancoin_values(apps, schema_editor):
    """Умножить исторические лимиты и балансы на 3."""
    SubscriptionTier = apps.get_model("subscriptions", "SubscriptionTier")
    UserSubscription = apps.get_model("subscriptions", "UserSubscription")
    for tier in SubscriptionTier.objects.all():
        tier.fancoin_per_purchase = int(tier.fancoin_per_purchase) * 3
        tier.save(update_fields=["fancoin_per_purchase"])
    for subscription in UserSubscription.objects.all():
        subscription.fancoin_balance = int(subscription.fancoin_balance) * 3
        subscription.save(update_fields=["fancoin_balance"])


def divide_fancoin_values(apps, schema_editor):
    """Откатить пересчёт FANcoin обратно к исходным значениям."""
    SubscriptionTier = apps.get_model("subscriptions", "SubscriptionTier")
    UserSubscription = apps.get_model("subscriptions", "UserSubscription")
    for tier in SubscriptionTier.objects.all():
        tier.fancoin_per_purchase = int(tier.fancoin_per_purchase) // 3
        tier.save(update_fields=["fancoin_per_purchase"])
    for subscription in UserSubscription.objects.all():
        subscription.fancoin_balance = int(subscription.fancoin_balance) // 3
        subscription.save(update_fields=["fancoin_balance"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "sparring",
            "0015_rename_sparring_sp_inviter_4f8a1d_idx_sparring_sp_inviter_001ec2_idx_and_more",
        ),
        ("subscriptions", "0016_subscription_registration_balance"),
        ("tournaments", "0045_tournament_tournaments_status_9d8850_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptiontier",
            old_name="max_tournaments",
            new_name="fancoin_per_purchase",
        ),
        migrations.RenameField(
            model_name="usersubscription",
            old_name="tournament_registration_balance",
            new_name="fancoin_balance",
        ),
        migrations.AlterField(
            model_name="subscriptiontier",
            name="fancoin_per_purchase",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Сколько FANcoin начисляется при покупке или продлении этого тарифа.",
                verbose_name="FANcoin за покупку",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptiontier",
            name="is_unlimited",
            field=models.BooleanField(
                default=False, verbose_name="Неограниченный FANcoin"
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="fancoin_balance",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Баланс FANcoin, который пополняется при покупке подписки и расходуется на регистрации турниров и состоявшиеся спарринги.",
                verbose_name="Баланс FANcoin",
            ),
        ),
        migrations.RunPython(multiply_fancoin_values, divide_fancoin_values),
        migrations.CreateModel(
            name="FancoinTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(verbose_name="Количество FANcoin"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("charge", "Списание"), ("refund", "Возврат")],
                        max_length=12,
                        verbose_name="Направление операции",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("tournament_registration", "Регистрация на турнир"),
                            ("tournament_cancel", "Отмена турнира"),
                            ("sparring_singles", "Состоявшийся одиночный спарринг"),
                            ("sparring_doubles", "Состоявшийся парный спарринг"),
                            ("sparring_team", "Состоявшийся командный спарринг"),
                        ],
                        max_length=64,
                        verbose_name="Причина операции",
                    ),
                ),
                (
                    "balance_after",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Баланс после операции"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата операции"
                    ),
                ),
                (
                    "doubles_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fancoin_transactions",
                        to="sparring.doublesmatchrequest",
                        verbose_name="Командная серия",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fancoin_transactions",
                        to="tournaments.match",
                        verbose_name="Матч",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fancoin_transactions",
                        to="tournaments.tournament",
                        verbose_name="Турнир",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fancoin_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция FANcoin",
                "verbose_name_plural": "Транзакции FANcoin",
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "match", "reason"),
                        name="uniq_fancoin_user_match_reason",
                    )
                ],
            },
        ),
    ]
