# Generated by Django 6.0.1 on 2026-04-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0017_remove_subscriptiontier_max_tournaments_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fancointransaction",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Транзакция FAN-token",
                "verbose_name_plural": "Транзакции FAN-token",
            },
        ),
        migrations.AlterField(
            model_name="fancointransaction",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Количество FT"),
        ),
        migrations.AlterField(
            model_name="subscriptiontier",
            name="fancoin_per_purchase",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Сколько FAN-token начисляется при покупке или продлении этого тарифа.",
                verbose_name="FAN-token за покупку",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptiontier",
            name="is_unlimited",
            field=models.BooleanField(
                default=False, verbose_name="Неограниченный FAN-token"
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="fancoin_balance",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Баланс FAN-token, который пополняется при покупке подписки и расходуется на регистрации турниров и состоявшиеся спарринги.",
                verbose_name="Баланс FT",
            ),
        ),
    ]
