# Generated by Django 6.0.1 on 2026-07-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0018_alter_fancointransaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fancointransaction",
            name="reason",
            field=models.CharField(
                choices=[
                    ("tournament_registration", "Регистрация на турнир"),
                    ("tournament_cancel", "Отмена турнира"),
                    ("tournament_withdrawal", "Снятие с турнира"),
                    ("sparring_singles", "Состоявшийся одиночный спарринг"),
                    ("sparring_doubles", "Состоявшийся парный спарринг"),
                    ("sparring_team", "Состоявшийся командный спарринг"),
                ],
                max_length=64,
                verbose_name="Причина операции",
            ),
        ),
    ]
