# Generated by Django 6.0.1 on 2026-09-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0019_tournament_withdrawal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="purchase_city",
            field=models.CharField(
                blank=True,
                help_text="Нормализованное значение населённого пункта на момент оплаты подписки (moscow / иное). Не менять вручную.",
                max_length=100,
                verbose_name="Населённый пункт при покупке",
            ),
        ),
    ]
