# Generated by Django 6.0.1 on 2026-03-14 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import config.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tournaments", "0041_alter_tournamentphoto_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Официальное название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL-идентификатор"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("address", models.TextField(verbose_name="Адрес")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to="clubs/",
                        validators=[config.validators.validate_image_max_2mb],
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Контактный email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
                ),
                (
                    "admin_name",
                    models.CharField(max_length=255, verbose_name="ФИО ответственного"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Публичная страница"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("suspended", "Заблокирован"),
                            ("trial", "Пробный период"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Конец пробного периода"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Клуб",
                "verbose_name_plural": "Клубы",
                "ordering": ["name"],
            },
            bases=(config.validators.CompressImageFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ClubInviteLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=64, unique=True, verbose_name="Токен"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Срок действия"
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Лимит переходов"
                    ),
                ),
                (
                    "use_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Счётчик использований"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_links",
                        to="clubs.club",
                        verbose_name="Клуб",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инвайт-ссылка",
                "verbose_name_plural": "Инвайт-ссылки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClubMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Администратор"),
                            ("manager", "Менеджер"),
                            ("player", "Игрок"),
                        ],
                        max_length=20,
                        verbose_name="Роль в клубе",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("invited", "Приглашён"),
                            ("removed", "Исключён"),
                        ],
                        max_length=20,
                        verbose_name="Статус участия",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата вступления"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="clubs.club",
                        verbose_name="Клуб",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_club_members",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто пригласил",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник клуба",
                "verbose_name_plural": "Участники клуба",
                "ordering": ["club", "user"],
                "unique_together": {("club", "user")},
            },
        ),
        migrations.CreateModel(
            name="ClubMembershipFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма взноса"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="Валюта"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("monthly", "Ежемесячно"),
                            ("quarterly", "Ежеквартально"),
                            ("yearly", "Ежегодно"),
                        ],
                        max_length=20,
                        verbose_name="Период",
                    ),
                ),
                (
                    "period_start_day",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="День начала периода (1–28)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание для игроков"),
                ),
                (
                    "restrict_tournament_access",
                    models.BooleanField(
                        default=False,
                        verbose_name="Блокировать доступ к турнирам неоплатившим",
                    ),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        choices=[("yookassa", "ЮKassa"), ("stripe", "Stripe")],
                        max_length=50,
                        verbose_name="Провайдер оплаты",
                    ),
                ),
                (
                    "payment_api_key",
                    models.TextField(
                        blank=True, verbose_name="API-ключ (хранить зашифрованным)"
                    ),
                ),
                (
                    "payment_shop_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID магазина (ЮKassa)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Включена система взносов"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_fees",
                        to="clubs.club",
                        verbose_name="Клуб",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка взносов клуба",
                "verbose_name_plural": "Настройки взносов клуба",
                "ordering": ["club", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClubFeePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "period_label",
                    models.CharField(
                        max_length=50, verbose_name="Период (напр. 2026-03)"
                    ),
                ),
                ("paid_at", models.DateTimeField(verbose_name="Дата оплаты")),
                (
                    "method",
                    models.CharField(
                        choices=[("online", "Онлайн"), ("manual", "Вручную")],
                        max_length=20,
                        verbose_name="Способ",
                    ),
                ),
                (
                    "payment_ref",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="ID транзакции провайдера",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_payments",
                        to="clubs.club",
                        verbose_name="Клуб",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто отметил вручную",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_payments",
                        to="clubs.clubmember",
                        verbose_name="Участник",
                    ),
                ),
                (
                    "fee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="clubs.clubmembershipfee",
                        verbose_name="Настройка взноса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата взноса",
                "verbose_name_plural": "Оплаты взносов",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.CreateModel(
            name="ClubRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=0, verbose_name="Текущий рейтинг (очки)"
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Место в рейтинге"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="clubs.club",
                        verbose_name="Клуб",
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_rating",
                        to="clubs.clubmember",
                        verbose_name="Участник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейтинг в клубе",
                "verbose_name_plural": "Рейтинги в клубе",
                "ordering": ["club", "-points"],
            },
        ),
        migrations.CreateModel(
            name="ClubRatingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_before", models.IntegerField(verbose_name="Очки до")),
                ("points_after", models.IntegerField(verbose_name="Очки после")),
                ("delta", models.IntegerField(verbose_name="Изменение (±)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "club_rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="clubs.clubrating",
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tournaments.tournament",
                        verbose_name="Турнир",
                    ),
                ),
            ],
            options={
                "verbose_name": "История рейтинга",
                "verbose_name_plural": "История рейтингов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClubSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("start", "Старт"),
                            ("basic", "Базовый"),
                            ("pro", "Про"),
                        ],
                        max_length=20,
                        verbose_name="Тариф",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("monthly", "Помесячно"), ("yearly", "Ежегодно")],
                        max_length=20,
                        verbose_name="Период оплаты",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма оплаты"
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="Начало подписки")),
                ("ends_at", models.DateTimeField(verbose_name="Конец подписки")),
                (
                    "auto_renew",
                    models.BooleanField(default=False, verbose_name="Автопродление"),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Провайдер оплаты"
                    ),
                ),
                (
                    "payment_ref",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ссылка на транзакцию"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активна"),
                            ("expired", "Истекла"),
                            ("cancelled", "Отменена"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="clubs.club",
                        verbose_name="Клуб",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка клуба",
                "verbose_name_plural": "Подписки клубов",
                "ordering": ["-ends_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClubTournamentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("approved", "Одобрена"),
                            ("rejected", "Отклонена"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Комментарий при заявке"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата ответа"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "applicant_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_applications",
                        to="clubs.club",
                        verbose_name="Клуб-заявитель",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто ответил",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_applications",
                        to="tournaments.tournament",
                        verbose_name="Турнир",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка клуба на турнир",
                "verbose_name_plural": "Заявки клубов на турниры",
                "ordering": ["-created_at"],
                "unique_together": {("tournament", "applicant_club")},
            },
        ),
    ]
