# Generated by Django 6.0.1 on 2026-03-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0005_player_plan_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Должен совпадать с ClubPlan: start, basic, pro",
                        max_length=20,
                        unique=True,
                        verbose_name="Код тарифа",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Краткое описание для отображения при выборе тарифа",
                        verbose_name="Описание возможностей",
                    ),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Цена за месяц (₽)",
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Цена за год (₽)",
                    ),
                ),
                (
                    "max_tournaments_per_month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Пусто — без лимита",
                        null=True,
                        verbose_name="Лимит турниров в месяц",
                    ),
                ),
                (
                    "trial_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Для тарифа Старт обычно 14",
                        verbose_name="Пробный период (дней)",
                    ),
                ),
                (
                    "is_public_page",
                    models.BooleanField(
                        default=True,
                        help_text="На тарифе Старт — обычно False",
                        verbose_name="Публичная страница клуба",
                    ),
                ),
                (
                    "is_open_interclub",
                    models.BooleanField(
                        default=False,
                        help_text="Доступно только для тарифа Про",
                        verbose_name="Межклубные турниры",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф платформы",
                "verbose_name_plural": "Тарифы платформы",
                "ordering": ["sort_order", "slug"],
            },
        ),
    ]
