# Generated by Django 6.0.1 on 2026-03-16 16:12

from django.db import migrations, models


def set_default_max_members(apps, schema_editor):
    """Устанавливает лимиты участников для существующих тарифов."""
    PlatformPlan = apps.get_model("clubs", "PlatformPlan")
    PlatformPlan.objects.filter(slug="start").update(max_members=20)
    PlatformPlan.objects.filter(slug="basic").update(max_members=100)
    PlatformPlan.objects.filter(slug="pro").update(max_members=None)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_populate_platform_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformplan",
            name="max_members",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Пусто — без лимита. Учитываются активные и приглашённые.",
                null=True,
                verbose_name="Лимит участников клуба",
            ),
        ),
        migrations.RunPython(set_default_max_members, noop),
    ]
