# Generated by Django 6.0.1 on 2026-03-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0009_add_club_hero_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clubplanslotusage",
            options={
                "ordering": ["-period_year", "-period_month", "club_member_id"],
                "verbose_name": "Учёт лимитов тарифа",
                "verbose_name_plural": "Учёт лимитов тарифов",
            },
        ),
        migrations.RemoveConstraint(
            model_name="clubplayerplan",
            name="club_player_plan_monthly_slots_gte_0",
        ),
        migrations.RemoveConstraint(
            model_name="clubplayerplan",
            name="club_player_plan_rollover_cap_gte_0",
        ),
        migrations.RemoveConstraint(
            model_name="clubplayerplan",
            name="club_player_plan_rollover_cap_when_disabled",
        ),
        migrations.RemoveField(
            model_name="clubplanslotusage",
            name="rollover_in",
        ),
        migrations.RemoveField(
            model_name="clubplanslotusage",
            name="rollover_out",
        ),
        migrations.RemoveField(
            model_name="clubplanslotusage",
            name="slots_used",
        ),
        migrations.AlterField(
            model_name="clubplayerplan",
            name="max_tournaments_per_month",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Пусто — без лимита. Платные однодневные турниры не расходуют лимит.",
                null=True,
                verbose_name="Лимит турниров в месяц",
            ),
        ),
        migrations.RemoveField(
            model_name="clubplayerplan",
            name="allow_rollover_slots",
        ),
        migrations.RemoveField(
            model_name="clubplayerplan",
            name="monthly_slots",
        ),
        migrations.RemoveField(
            model_name="clubplayerplan",
            name="rollover_cap",
        ),
    ]
