# Generated by Django 6.0.1 on 2026-03-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0015_clubplayerplan_duration_and_unlimited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubfeepayment",
            name="method",
            field=models.CharField(
                choices=[
                    ("online", "Онлайн"),
                    ("balance", "Баланс клуба"),
                    ("manual", "Вручную"),
                ],
                max_length=20,
                verbose_name="Способ",
            ),
        ),
        migrations.AlterField(
            model_name="clubmembershipfee",
            name="payment_provider",
            field=models.CharField(
                blank=True,
                choices=[("yookassa", "ЮKassa")],
                max_length=50,
                verbose_name="Провайдер оплаты",
            ),
        ),
    ]
