# Generated by Django 6.0.1 on 2026-04-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0018_clubplayerplan_registration_limit_period"),
        ("tournaments", "0043_club_tournament_proxy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubTournament",
            fields=[],
            options={
                "verbose_name": "Турнир клуба",
                "verbose_name_plural": "Турниры клубов",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tournaments.tournament",),
        ),
        migrations.AlterField(
            model_name="clubplayerplan",
            name="max_tournaments_per_month",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Обязателен, если безлимитные регистрации выключены.",
                null=True,
                verbose_name="Лимит турниров",
            ),
        ),
    ]
