# Generated by Django 6.0.1 on 2026-09-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0019_club_tournament_proxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Населённый пункт"),
        ),
    ]
