# Generated by Django 6.0.1 on 2026-09-21 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0020_locality_settlement_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubsubscription",
            name="started_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Начало подписки"
            ),
        ),
    ]
