# Generated by Django 6.0.1 on 2026-09-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0021_clubsubscription_started_at_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("club_blocked", "Клуб заблокирован"),
                    ("club_unblocked", "Клуб разблокирован"),
                    ("plan_changed", "Тариф изменён"),
                    ("subscription_extended", "Подписка продлена"),
                    ("club_deleted", "Клуб удалён"),
                    ("trial_reset", "Trial сброшен"),
                    ("club_auto_suspended", "Клуб автоматически приостановлен"),
                    ("club_auto_deleted", "Клуб автоматически удалён"),
                    ("settings_changed", "Настройки платформы изменены"),
                    ("club_admin_assigned", "Назначен администратор клуба"),
                ],
                max_length=50,
                verbose_name="Действие",
            ),
        ),
    ]
