# Generated by Django 6.0.1 on 2026-03-10 10:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method_id",
                    models.CharField(
                        help_text="Идентификатор payment_method из API ЮKassa для автоплатежей.",
                        max_length=128,
                        unique=True,
                        verbose_name="ID способа оплаты в ЮKassa",
                    ),
                ),
                (
                    "card_last4",
                    models.CharField(
                        blank=True,
                        help_text="Используется только для отображения пользователю.",
                        max_length=4,
                        verbose_name="Последние 4 цифры карты",
                    ),
                ),
                (
                    "card_exp_month",
                    models.CharField(
                        blank=True,
                        help_text="Месяц окончания срока действия карты в формате MM.",
                        max_length=2,
                        verbose_name="Месяц окончания",
                    ),
                ),
                (
                    "card_exp_year",
                    models.CharField(
                        blank=True,
                        help_text="Год окончания срока действия карты в формате YYYY.",
                        max_length=4,
                        verbose_name="Год окончания",
                    ),
                ),
                (
                    "card_network",
                    models.CharField(
                        blank=True,
                        help_text="Например: Visa, Mastercard, Mir.",
                        max_length=32,
                        verbose_name="Платёжная система",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Если выключено — карта больше не используется для автосписаний и не показывается пользователю.",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "is_default_for_subscriptions",
                    models.BooleanField(
                        default=True,
                        help_text="Если включено — этот способ оплаты используется для автосписаний за подписку.",
                        verbose_name="Использовать для автопродления подписки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_payment_methods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сохранённый способ оплаты",
                "verbose_name_plural": "Сохранённые способы оплаты",
                "ordering": ["-created_at"],
            },
        ),
    ]
