# Generated by Django 6.0.1 on 2026-03-10 14:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Подписка"),
                            ("tournament", "Турнир"),
                            ("donation", "Донат"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Тип оплаты",
                    ),
                ),
                (
                    "item_id",
                    models.CharField(
                        blank=True,
                        help_text="ID тарифа, турнира или другого объекта оплаты.",
                        max_length=64,
                        verbose_name="ID объекта",
                    ),
                ),
                (
                    "item_label",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Наименование"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=8, verbose_name="Валюта"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_index=True,
                        default="succeeded",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "yookassa_payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        verbose_name="ID платежа в ЮKassa",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, verbose_name="Рекуррентный платёж"
                    ),
                ),
                (
                    "autopay_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Показывает, включал ли пользователь автопродление при оплате.",
                        verbose_name="С автосписанием",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Дополнительные данные"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Дата оплаты",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "запись об оплате",
                "verbose_name_plural": "записи об оплатах",
                "ordering": ["-paid_at", "-id"],
            },
        ),
    ]
