# Generated by Django 6.0.1 on 2026-03-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_savedpaymentmethod_club_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("subscription", "Подписка"),
                    ("club_plan", "Тариф клуба"),
                    ("club_fee", "Членский взнос клуба"),
                    ("tournament", "Турнир"),
                    ("donation", "Донат"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="Тип оплаты",
            ),
        ),
    ]
