# Generated by Django 6.0.1 on 2026-01-22 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='forehand',
            field=models.CharField(choices=[('right', 'Правша'), ('left', 'Левша')], default='right', max_length=10, verbose_name='Forehand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=10, verbose_name='Пол'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('expert', 'Эксперт')], default='intermediate', max_length=20, verbose_name='Уровень мастерства'),
            preserve_default=False,
        ),
    ]
