# Generated by Django 6.0.1 on 2026-01-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_map_skill_level_to_ntrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('futures', 'Фьючерс'), ('base', 'База'), ('tour', 'Тур'), ('hard', 'Хард'), ('challenger', 'Челленджер'), ('masters', 'Мастерс')], default='base', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_level',
            field=models.CharField(choices=[('1.0', '1.0 — Начальный'), ('2.0', '2.0 — Начинающий'), ('2.5', '2.5 — Ниже среднего'), ('3.0', '3.0 — Средний'), ('3.5', '3.5 — Выше среднего'), ('4.0', '4.0 — Уверенный'), ('4.5', '4.5 — Продвинутый'), ('5.0', '5.0 — Сильный'), ('5.5', '5.5 — Очень сильный'), ('6.0', '6.0 — Полупрофи'), ('7.0', '7.0 — Профи')], max_length=20, verbose_name='Уровень мастерства'),
        ),
    ]
