# Generated by Django 6.0.1 on 2026-01-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_player_category_alter_player_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
    ]
