# Generated by Django 6.0.1 on 2026-01-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_map_skill_level_to_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='skill_level',
            field=models.CharField(choices=[('novice', 'Новичок'), ('amateur', 'Любитель'), ('experienced', 'Опытный'), ('advanced', 'Продвинутый'), ('professional', 'Профессионал')], max_length=20, verbose_name='Уровень мастерства'),
        ),
    ]
