# Generated by Django 6.0.1 on 2026-01-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_player_max_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='category',
        ),
    ]
