# Generated by Django 6.0.1 on 2026-01-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_registration_optional_fields_forehand_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_bye',
            field=models.BooleanField(default=False, help_text='Служебный игрок для матчей «игрок — свободный круг» при нечётном числе участников.', verbose_name='Свободный круг (bye)'),
        ),
    ]
