# Generated by Django 6.0.1 on 2026-02-05 14:26

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_create_bye_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', validators=[config.validators.validate_image_max_2mb], verbose_name='Аватар'),
        ),
    ]
