# Generated by Django 6.0.1 on 2026-02-11 13:05

from django.db import migrations


def init_hidden_rating(apps, schema_editor):
    """Copy total_points to hidden_rating for all existing players."""
    Player = apps.get_model("users", "Player")
    for player in Player.objects.all():
        player.hidden_rating = float(player.total_points)
        player.save(update_fields=["hidden_rating"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_add_hidden_rating'),
    ]

    operations = [
        migrations.RunPython(init_hidden_rating, migrations.RunPython.noop),
    ]
