# Generated by Django 6.0.1 on 2026-02-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_change_total_points_to_float"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="is_verified",
            field=models.BooleanField(default=True, verbose_name="Подтверждён"),
        ),
    ]
