# Generated by Django 6.0.1 on 2026-02-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_set_is_verified_default_true"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="skill_level",
            field=models.CharField(
                choices=[
                    ("novice", "Новичок"),
                    ("amateur", "Любитель"),
                    ("experienced", "Опытный"),
                    ("advanced", "Мастерс"),
                    ("professional", "Профессионал"),
                ],
                default="novice",
                help_text="Определяется тестом уровня силы или админкой. Пользователь не редактирует вручную.",
                max_length=20,
                verbose_name="Уровень силы",
            ),
        ),
    ]
