# Generated by Django 6.0.1 on 2026-02-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_rename_advanced_to_masters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="total_points",
            field=models.FloatField(
                default=0.0,
                help_text="Рейтинг силы (FAN). Обновляется после каждого матча.",
                verbose_name="Рейтинг FAN",
            ),
        ),
    ]
