# Generated by Django 6.0.1 on 2026-02-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_alter_player_total_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="ntrp_level",
            field=models.DecimalField(
                decimal_places=1, default=1.5, max_digits=3, verbose_name="Уровень силы"
            ),
        ),
    ]
