# Generated by Django 6.0.1 on 2026-02-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_update_ntrp_default_to_1_5"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="has_ever_paid_subscription",
            field=models.BooleanField(
                default=False,
                help_text="Становится True после первой оплаты любой подписки (для акции «первая за 1 ₽»).",
                verbose_name="Уже покупал подписку",
            ),
        ),
    ]
