# Generated by Django 6.0.1 on 2026-04-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_alter_player_max_contact"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["is_bye", "is_verified"], name="users_playe_is_bye_fd7aa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["city", "skill_level"], name="users_playe_city_3dd31c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["-total_points"], name="users_playe_total_p_05ea77_idx"
            ),
        ),
    ]
