# Generated by Django 6.0.1 on 2026-04-24 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_users_verified(apps, schema_editor) -> None:
    """Пометить существующих пользователей как подтверждённых."""
    user_model = apps.get_model("users", "User")
    user_model.objects.all().update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_player_users_playe_is_bye_fd7aa1_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=True, verbose_name="Email подтвержден"),
        ),
        migrations.RunPython(
            mark_existing_users_verified,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=128, unique=True, verbose_name="Токен"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Истекает")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Использован"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Токен подтверждения email",
                "verbose_name_plural": "Токены подтверждения email",
                "ordering": ["-created_at"],
            },
        ),
    ]
