# Generated by Django 6.0.1 on 2026-09-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_user_email_verified_emailverificationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Населённый пункт"
            ),
        ),
    ]
