# Generated by Django 6.0.1 on 2026-09-30 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_ntrp_level_hundredths"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerSportProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[("tennis", "Теннис"), ("padel", "Падел")],
                        db_index=True,
                        default="tennis",
                        max_length=20,
                        verbose_name="Вид спорта",
                    ),
                ),
                (
                    "total_points",
                    models.FloatField(
                        default=0.0,
                        help_text="Рейтинг силы в этом виде спорта.",
                        verbose_name="Рейтинг FAN",
                    ),
                ),
                (
                    "hidden_rating",
                    models.FloatField(
                        default=0.0,
                        help_text="Теневой рейтинг вида спорта.",
                        verbose_name="Скрытый рейтинг",
                    ),
                ),
                (
                    "ntrp_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=4,
                        verbose_name="Уровень силы",
                    ),
                ),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("novice", "Новичок"),
                            ("amateur", "Любитель"),
                            ("experienced", "Опытный"),
                            ("advanced", "Мастерс"),
                            ("professional", "Профессионал"),
                        ],
                        default="novice",
                        max_length=20,
                        verbose_name="Категория силы",
                    ),
                ),
                (
                    "matches_played",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Сыграно матчей"
                    ),
                ),
                (
                    "matches_won",
                    models.PositiveIntegerField(default=0, verbose_name="Побед"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sport_profiles",
                        to="users.player",
                        verbose_name="Игрок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль вида спорта",
                "verbose_name_plural": "Профили видов спорта",
                "indexes": [
                    models.Index(
                        fields=["sport", "-total_points"],
                        name="users_playe_sport_d8e230_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "sport"),
                        name="users_player_sport_profile_uniq",
                    )
                ],
            },
        ),
    ]
