# Generated by Django 6.0.1 on 2026-10-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_player_sport_profile_entry_level_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="skill_level",
            field=models.CharField(
                choices=[
                    ("novice", "Новичок"),
                    ("amateur", "Любитель"),
                    ("experienced", "Опытный"),
                    ("advanced", "Мастер"),
                    ("professional", "Профессионал"),
                ],
                default="novice",
                help_text="Определяется тестом уровня силы или админкой. Пользователь не редактирует вручную.",
                max_length=20,
                verbose_name="Уровень силы",
            ),
        ),
        migrations.AlterField(
            model_name="playersportprofile",
            name="skill_level",
            field=models.CharField(
                choices=[
                    ("novice", "Новичок"),
                    ("amateur", "Любитель"),
                    ("experienced", "Опытный"),
                    ("advanced", "Мастер"),
                    ("professional", "Профессионал"),
                ],
                default="novice",
                max_length=20,
                verbose_name="Категория силы",
            ),
        ),
    ]
