# Generated by Django 6.0.1 on 2026-02-25 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tournaments", "0039_add_skill_rating_models"),
        ("users", "0026_has_ever_paid_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerSkillAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(
                        choices=[
                            ("serve", "Подача"),
                            ("accuracy", "Точность"),
                            ("tactics", "Тактика"),
                            ("speed", "Скорость"),
                            ("endurance", "Выносливость"),
                            ("consistency", "Стабильность"),
                            ("net_play", "Игра у сетки"),
                            ("pressure_play", "Игра под давлением"),
                            ("fighting_spirit", "Боевой дух"),
                            ("communication", "Коммуникация"),
                            ("punctuality", "Пунктуальность"),
                            ("fairness", "Честная игра"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("average_raw", models.FloatField(default=0.0)),
                ("average_weighted", models.FloatField(default=0.0)),
                ("votes_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_aggregates",
                        to="users.player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Агрегат навыка игрока",
                "verbose_name_plural": "Агрегаты навыков игроков",
                "db_table": "player_ratings_skillaggregate",
                "indexes": [
                    models.Index(
                        fields=["player", "metric_name"],
                        name="player_rati_player__e5e5be_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "metric_name"),
                        name="player_ratings_unique_player_metric",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerSkillRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serve", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("accuracy", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("tactics", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("speed", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("endurance", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "consistency",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("net_play", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "pressure_play",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "fighting_spirit",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "communication",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "punctuality",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("fairness", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_ratings_given",
                        to="users.player",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_ratings",
                        to="tournaments.match",
                    ),
                ),
                (
                    "to_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_ratings_received",
                        to="users.player",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка навыков соперника",
                "verbose_name_plural": "Оценки навыков соперников",
                "db_table": "player_ratings_skillrating",
                "indexes": [
                    models.Index(
                        fields=["to_player"], name="player_rati_to_play_974fa5_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "from_player"),
                        name="player_ratings_unique_match_from",
                    )
                ],
            },
        ),
    ]
