# Generated by Django 6.0.1 on 2026-02-27 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player_ratings", "0001_add_skill_rating_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillMetricConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(
                        choices=[
                            ("serve", "Подача"),
                            ("accuracy", "Точность"),
                            ("tactics", "Тактика"),
                            ("speed", "Скорость"),
                            ("endurance", "Выносливость"),
                            ("consistency", "Стабильность"),
                            ("net_play", "Игра у сетки"),
                            ("pressure_play", "Игра под давлением"),
                            ("fighting_spirit", "Боевой дух"),
                            ("communication", "Коммуникация"),
                            ("punctuality", "Пунктуальность"),
                            ("fairness", "Честная игра"),
                        ],
                        db_index=True,
                        max_length=30,
                        unique=True,
                        verbose_name="Системное имя метрики",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Будет показано в профиле игрока и в форме оценки соперника.",
                        max_length=100,
                        verbose_name="Название для отображения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Название метрики навыков",
                "verbose_name_plural": "Названия метрик навыков",
                "db_table": "player_ratings_skillmetricconfig",
            },
        ),
        migrations.AlterField(
            model_name="playerskillrating",
            name="accuracy",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="playerskillrating",
            name="communication",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="playerskillrating",
            name="consistency",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="playerskillrating",
            name="endurance",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="playerskillrating",
            name="fairness",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="playerskillrating",
            name="fighting_spirit",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="playerskillrating",
            name="net_play",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="playerskillrating",
            name="pressure_play",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="playerskillrating",
            name="punctuality",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="playerskillrating",
            name="serve",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="playerskillrating",
            name="speed",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="playerskillrating",
            name="tactics",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
