# Generated by Django 6.0.1 on 2026-02-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "player_ratings",
            "0002_skillmetricconfig_alter_playerskillrating_accuracy_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="skillmetricconfig",
            name="display_on_page",
            field=models.BooleanField(
                default=True,
                help_text="Если включено, метрика будет показана в профиле игрока и в форме оценки соперника.",
                verbose_name="Отображать на странице",
            ),
        ),
    ]
