# Generated by Django 6.0.1 on 2026-02-12 17:43

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='image',
            field=models.ImageField(upload_to='shop/products/', validators=[config.validators.validate_image_max_2mb], verbose_name='Фото'),
        ),
    ]
