# Generated by Django 6.0.1 on 2026-01-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('moscow', 'Москва'), ('spb', 'Санкт-Петербург')], default='moscow', max_length=20, verbose_name='Город')),
                ('desired_category', models.CharField(blank=True, choices=[('futures', 'Futures'), ('base', 'Base'), ('tour', 'Tour'), ('hard', 'Hard'), ('challenger', 'Challenger'), ('masters', 'Masters')], max_length=20, verbose_name='Желаемая категория партнёра')),
                ('description', models.TextField(help_text='Опишите себя, когда и где хотите играть', verbose_name='Описание')),
                ('preferred_days', models.CharField(blank=True, max_length=100, verbose_name='Предпочтительные дни')),
                ('preferred_time', models.CharField(blank=True, max_length=100, verbose_name='Предпочтительное время')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('closed', 'Закрыта')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Заявка на спарринг',
                'verbose_name_plural': 'Заявки на спарринг',
                'ordering': ['-created_at'],
            },
        ),
    ]
