# Generated by Django 6.0.1 on 2026-01-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparring', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparringrequest',
            name='desired_category',
            field=models.CharField(blank=True, choices=[('futures', 'Фьючерс'), ('base', 'База'), ('tour', 'Тур'), ('hard', 'Хард'), ('challenger', 'Челленджер'), ('masters', 'Мастерс')], max_length=20, verbose_name='Желаемая категория партнёра'),
        ),
    ]
