# Generated by Django 6.0.1 on 2026-01-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparring', '0003_alter_sparringrequest_desired_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparringrequest',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
    ]
