# Generated by Django 6.0.1 on 2026-02-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sparring", "0007_add_detailed_preferences_and_response_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sparringrequest",
            name="desired_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("novice", "Новичок"),
                    ("amateur", "Любитель"),
                    ("experienced", "Опытный"),
                    ("advanced", "Мастерс"),
                    ("professional", "Профессионал"),
                ],
                max_length=20,
                verbose_name="Желаемый уровень (NTRP)",
            ),
        ),
    ]
