# Generated by Django 6.0.1 on 2026-02-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sparring", "0008_alter_sparringrequest_desired_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparringrequest",
            name="is_friendly",
            field=models.BooleanField(
                default=False,
                help_text="Если отмечено, результат матча не влияет на рейтинг и NTRP ни автора, ни соперника.",
                verbose_name="Дружеский матч",
            ),
        ),
    ]
