# Generated by Django 6.0.1 on 2026-02-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sparring", "0009_add_is_friendly_to_sparring_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparringrequest",
            name="match_type",
            field=models.CharField(
                choices=[("singles", "Одиночная"), ("doubles", "Парная")],
                default="singles",
                max_length=20,
                verbose_name="Тип матча",
            ),
        ),
        migrations.AddField(
            model_name="sparringrequest",
            name="preferred_gender",
            field=models.CharField(
                choices=[
                    ("male", "Мужчины"),
                    ("female", "Женщины"),
                    ("open", "Смешанный"),
                    ("mixed", "Микст"),
                ],
                default="open",
                help_text="Для одиночных: пол соперника. Для парных: мужской/женский парный, смешанный или микст.",
                max_length=20,
                verbose_name="Предпочтительный пол",
            ),
        ),
        migrations.AlterField(
            model_name="sparringrequest",
            name="is_friendly",
            field=models.BooleanField(
                default=False,
                help_text="Если отмечено, результат матча не влияет на рейтинг и NTRP",
                verbose_name="Дружеский матч",
            ),
        ),
    ]
