# Generated by Django 6.0.1 on 2026-02-17 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sparring", "0010_add_match_type_and_preferred_gender"),
        ("tournaments", "0032_add_partner1_partner2_for_doubles_sparring"),
        ("users", "0024_alter_player_total_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoublesMatchRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Открыта"),
                            ("forming", "Формирование"),
                            ("ready", "Готова к подтверждению"),
                            ("confirmed", "Подтверждена (матч создан)"),
                            ("cancelled", "Отменена"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Город"),
                ),
                (
                    "preferred_gender",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Предпочтительный пол"
                    ),
                ),
                (
                    "is_friendly",
                    models.BooleanField(default=False, verbose_name="Дружеский матч"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Подтверждено"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doubles_match_requests_created",
                        to="users.player",
                        verbose_name="Автор заявки",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doubles_match_request",
                        to="tournaments.match",
                        verbose_name="Матч",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на парный спарринг 2×2",
                "verbose_name_plural": "Заявки на парный спарринг 2×2",
                "db_table": "doubles_sparring_match_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DoublesJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_side",
                    models.CharField(
                        choices=[
                            ("author", "Команда автора"),
                            ("opponent", "Команда соперников"),
                        ],
                        max_length=20,
                        verbose_name="Целевая команда",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("accepted", "Принят"),
                            ("rejected", "Отклонён"),
                            ("cancelled", "Отменён заявителем"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Обработано"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doubles_join_requests_created",
                        to="users.player",
                        verbose_name="Кто подал заявку",
                    ),
                ),
                (
                    "match_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="sparring.doublesmatchrequest",
                        verbose_name="Заявка на матч",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на присоединение (парный спарринг)",
                "verbose_name_plural": "Заявки на присоединение (парный спарринг)",
                "db_table": "doubles_sparring_join_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DoublesTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[
                            ("author", "Команда автора"),
                            ("opponent", "Команда соперников"),
                        ],
                        max_length=20,
                        verbose_name="Сторона",
                    ),
                ),
                (
                    "match_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="sparring.doublesmatchrequest",
                        verbose_name="Заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Команда (парный спарринг)",
                "verbose_name_plural": "Команды (парный спарринг)",
                "db_table": "doubles_sparring_team",
            },
        ),
        migrations.CreateModel(
            name="DoublesTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_captain",
                    models.BooleanField(default=False, verbose_name="Капитан команды"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doubles_team_memberships",
                        to="users.player",
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="sparring.doublesteam",
                        verbose_name="Команда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник команды (парный спарринг)",
                "verbose_name_plural": "Участники команд (парный спарринг)",
                "db_table": "doubles_sparring_team_member",
            },
        ),
        migrations.CreateModel(
            name="DoublesJoinRequestMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Порядок"),
                ),
                (
                    "join_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="sparring.doublesjoinrequest",
                        verbose_name="Заявка на присоединение",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doubles_join_request_memberships",
                        to="users.player",
                        verbose_name="Игрок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник заявки на присоединение",
                "verbose_name_plural": "Участники заявок на присоединение",
                "db_table": "doubles_sparring_join_request_member",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("join_request", "player"),
                        name="doubles_join_req_member_unique_player",
                    ),
                    models.UniqueConstraint(
                        fields=("join_request", "order"),
                        name="doubles_join_req_member_unique_order",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="doublesmatchrequest",
            index=models.Index(
                fields=["status", "created_at"], name="doubles_spa_status_1a262b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doublesjoinrequest",
            index=models.Index(
                fields=["match_request", "status"],
                name="doubles_spa_match_r_505820_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="doublesteam",
            index=models.Index(
                fields=["match_request", "side"], name="doubles_spa_match_r_59704a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="doublesteam",
            constraint=models.UniqueConstraint(
                fields=("match_request", "side"),
                name="doubles_team_unique_side_per_request",
            ),
        ),
        migrations.AddIndex(
            model_name="doublesteammember",
            index=models.Index(fields=["team"], name="doubles_spa_team_id_4616a7_idx"),
        ),
        migrations.AddIndex(
            model_name="doublesteammember",
            index=models.Index(
                fields=["player"], name="doubles_spa_player__de08b8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="doublesteammember",
            constraint=models.UniqueConstraint(
                fields=("team", "player"),
                name="doubles_team_member_unique_player_per_team",
            ),
        ),
    ]
