# Generated by Django 6.0.1 on 2026-02-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sparring", "0011_add_doubles_match_request_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="doublesmatchrequest",
            name="desired_age_max",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Максимальный возраст партнёров"
            ),
        ),
        migrations.AddField(
            model_name="doublesmatchrequest",
            name="desired_age_min",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Минимальный возраст партнёров"
            ),
        ),
        migrations.AddField(
            model_name="doublesmatchrequest",
            name="desired_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("novice", "Новичок"),
                    ("amateur", "Любитель"),
                    ("experienced", "Опытный"),
                    ("advanced", "Мастерс"),
                    ("professional", "Профессионал"),
                ],
                max_length=20,
                verbose_name="Желаемый уровень партнёров",
            ),
        ),
        migrations.AddField(
            model_name="doublesmatchrequest",
            name="preferred_days",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Предпочтительные дни"
            ),
        ),
        migrations.AddField(
            model_name="doublesmatchrequest",
            name="preferred_location",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Предпочтительное место"
            ),
        ),
        migrations.AddField(
            model_name="doublesmatchrequest",
            name="preferred_time",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Предпочтительное время"
            ),
        ),
        migrations.AlterField(
            model_name="sparringrequest",
            name="desired_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("novice", "Новичок"),
                    ("amateur", "Любитель"),
                    ("experienced", "Опытный"),
                    ("advanced", "Мастерс"),
                    ("professional", "Профессионал"),
                ],
                max_length=20,
                verbose_name="Желаемый уровень силы",
            ),
        ),
        migrations.AlterField(
            model_name="sparringrequest",
            name="is_friendly",
            field=models.BooleanField(
                default=False,
                help_text="Если отмечено, результат матча не влияет на рейтинг и силу",
                verbose_name="Дружеский матч",
            ),
        ),
    ]
