# Generated by Django 6.0.1 on 2026-03-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sparring", "0012_add_doubles_details_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="doublesmatchrequest",
            name="kind",
            field=models.CharField(
                choices=[("classic", "Парный 2×2"), ("team", "Командный спарринг")],
                db_index=True,
                default="classic",
                help_text="Парный матч 2×2 или командный спарринг.",
                max_length=20,
                verbose_name="Тип заявки",
            ),
        ),
    ]
