# Generated by Django 6.0.1 on 2026-04-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sparring", "0014_sparring_invitation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sparringinvitation",
            new_name="sparring_sp_inviter_001ec2_idx",
            old_name="sparring_sp_inviter_4f8a1d_idx",
        ),
        migrations.RenameIndex(
            model_name="sparringinvitation",
            new_name="sparring_sp_invitee_a9a2b8_idx",
            old_name="sparring_sp_invitee_8b2c3e_idx",
        ),
        migrations.AlterField(
            model_name="sparringrequest",
            name="preferred_gender",
            field=models.CharField(
                choices=[
                    ("male", "Мужчины"),
                    ("female", "Женщины"),
                    ("open", "Любой"),
                    ("mixed", "Микст"),
                ],
                default="open",
                help_text="Для одиночных: пол соперника. Для парных: мужской/женский парный, любой или микст.",
                max_length=20,
                verbose_name="Предпочтительный пол",
            ),
        ),
    ]
