# Generated by Django 6.0.1 on 2026-09-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sparring",
            "0015_rename_sparring_sp_inviter_4f8a1d_idx_sparring_sp_inviter_001ec2_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="doublesmatchrequest",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Населённый пункт"
            ),
        ),
        migrations.AlterField(
            model_name="sparringrequest",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Населённый пункт"),
        ),
    ]
