# Generated by Django 6.0.1 on 2026-09-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sparring", "0016_rename_city_verbose_to_locality"),
    ]

    operations = [
        migrations.AddField(
            model_name="doublesmatchrequest",
            name="sport",
            field=models.CharField(
                choices=[("tennis", "Теннис"), ("padel", "Падел")],
                db_index=True,
                default="tennis",
                max_length=20,
                verbose_name="Вид спорта",
            ),
        ),
        migrations.AddField(
            model_name="sparringrequest",
            name="sport",
            field=models.CharField(
                choices=[("tennis", "Теннис"), ("padel", "Падел")],
                db_index=True,
                default="tennis",
                max_length=20,
                verbose_name="Вид спорта",
            ),
        ),
    ]
