# Generated by Django 6.0.1 on 2026-10-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sparring", "0017_sport_padel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doublesmatchrequest",
            name="desired_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("novice", "Новичок"),
                    ("amateur", "Любитель"),
                    ("experienced", "Опытный"),
                    ("advanced", "Мастер"),
                    ("professional", "Профессионал"),
                ],
                max_length=20,
                verbose_name="Желаемый уровень партнёров",
            ),
        ),
        migrations.AlterField(
            model_name="sparringrequest",
            name="desired_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("novice", "Новичок"),
                    ("amateur", "Любитель"),
                    ("experienced", "Опытный"),
                    ("advanced", "Мастер"),
                    ("professional", "Профессионал"),
                ],
                max_length=20,
                verbose_name="Желаемый уровень силы",
            ),
        ),
    ]
