# Generated by Django 6.0.1 on 2026-01-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
    ]
