# Generated by Django 6.0.1 on 2026-01-28 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_alter_court_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('applicant_name', models.CharField(max_length=200, verbose_name='Контактное лицо')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='Email заявителя')),
                ('applicant_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон заявителя')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('surface', models.CharField(choices=[('hard', 'Хард'), ('clay', 'Грунт'), ('grass', 'Трава'), ('indoor', 'Закрытый хард')], default='hard', max_length=20, verbose_name='Покрытие')),
                ('courts_count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество кортов')),
                ('has_lighting', models.BooleanField(default=True, verbose_name='Освещение')),
                ('is_indoor', models.BooleanField(default=False, verbose_name='Крытый')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('image', models.ImageField(blank=True, upload_to='courts/applications/', verbose_name='Фото')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена/час')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('court', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='courts.court', verbose_name='Созданный корт')),
            ],
            options={
                'verbose_name': 'Заявка на добавление корта',
                'verbose_name_plural': 'Заявки на добавление корта',
                'ordering': ['-created_at'],
            },
        ),
    ]
