# Generated by Django 6.0.1 on 2026-02-12 17:43

from django.db import migrations, models

import config.validators


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0005_court_rating_and_extra_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="courts/",
                validators=[config.validators.validate_image_max_2mb],
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="courtapplication",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="courts/applications/",
                validators=[config.validators.validate_image_max_2mb],
                verbose_name="Фото",
            ),
        ),
    ]
