# Generated by Django 6.0.1 on 2026-02-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0007_surface_free_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="has_training",
            field=models.BooleanField(default=False, verbose_name="Тренировки"),
        ),
        migrations.AddField(
            model_name="court",
            name="is_outdoor",
            field=models.BooleanField(
                default=False,
                help_text="У одного корта могут быть и крытые, и открытые поля.",
                verbose_name="Открытый",
            ),
        ),
        migrations.AddField(
            model_name="court",
            name="parking_nearby",
            field=models.BooleanField(default=False, verbose_name="Парковка рядом"),
        ),
        migrations.AddField(
            model_name="court",
            name="parking_on_site",
            field=models.BooleanField(
                default=False, verbose_name="Парковка на территории"
            ),
        ),
        migrations.AddField(
            model_name="court",
            name="racket_rental",
            field=models.BooleanField(default=False, verbose_name="Аренда ракеток"),
        ),
        migrations.AddField(
            model_name="court",
            name="racket_stringing",
            field=models.BooleanField(default=False, verbose_name="Перетяжка ракеток"),
        ),
        migrations.AddField(
            model_name="court",
            name="rental_price_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Цена аренды до (₽/час)",
            ),
        ),
        migrations.AddField(
            model_name="court",
            name="rental_price_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Цена аренды от (₽/час)",
            ),
        ),
    ]
