# Generated by Django 6.0.1 on 2026-03-05 15:09

from django.db import migrations, models

import config.validators


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0009_courtphoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courtphoto",
            name="image",
            field=models.ImageField(
                upload_to="courts/gallery/",
                validators=[config.validators.validate_image_max_2mb],
                verbose_name="Фото",
            ),
        ),
    ]
