# Generated by Django 6.0.1 on 2026-08-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_geoarea"),
        ("courts", "0013_court_split_surface_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="geo_area",
            field=models.ForeignKey(
                blank=True,
                help_text="Зона Москвы или город области, из справочника. Поле «Район города» — свободный текст.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courts",
                to="core.geoarea",
                verbose_name="Зона / город",
            ),
        ),
        migrations.AddField(
            model_name="court",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[("moscow", "Москва"), ("moscow_oblast", "Московская область")],
                db_index=True,
                default="",
                help_text="Москва или область. Определяет набор доступных зон и городов.",
                max_length=32,
                verbose_name="Регион",
            ),
        ),
    ]
