# Generated by Django 6.0.1 on 2026-08-27 07:42

from django.db import migrations, models
from django.db.models import Q


def merge_parking_flags(apps, schema_editor) -> None:
    """Перенести две старые галочки парковки в одно поле has_parking."""
    Court = apps.get_model("courts", "Court")
    Court.objects.filter(Q(parking_on_site=True) | Q(parking_nearby=True)).update(
        has_parking=True
    )


def split_parking_flags(apps, schema_editor) -> None:
    """Вернуть has_parking в parking_on_site при откате миграции."""
    Court = apps.get_model("courts", "Court")
    Court.objects.filter(has_parking=True).update(parking_on_site=True)


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0014_court_geo_area_court_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="has_parking",
            field=models.BooleanField(
                default=False, verbose_name="Автомобильная парковка"
            ),
        ),
        migrations.RunPython(merge_parking_flags, split_parking_flags),
        migrations.RemoveField(
            model_name="court",
            name="parking_nearby",
        ),
        migrations.RemoveField(
            model_name="court",
            name="parking_on_site",
        ),
    ]
