# Generated by Django 6.0.1 on 2026-08-27 08:45

import re

from django.db import migrations, models

WORKING_HOURS_LINE = re.compile(
    r"^\s*Время работы\s*:\s*(.+?)\s*$",
    re.IGNORECASE,
)


def copy_working_hours_from_description(apps, schema_editor) -> None:
    """Если описание — только строка «Время работы: …», перенести её в поле."""
    Court = apps.get_model("courts", "Court")
    max_len = int(Court._meta.get_field("working_hours").max_length or 255)
    to_update = []
    for court in Court.objects.exclude(description=""):
        text = (court.description or "").strip()
        match = WORKING_HOURS_LINE.match(text)
        if not match:
            continue
        hours = match.group(1).strip()
        if not hours or len(hours) > max_len:
            continue
        court.working_hours = hours
        court.description = ""
        to_update.append(court)
    if to_update:
        Court.objects.bulk_update(to_update, ["working_hours", "description"])


def restore_working_hours_into_description(apps, schema_editor) -> None:
    """Вернуть часы в описание, если отдельного текста нет."""
    Court = apps.get_model("courts", "Court")
    to_update = []
    for court in Court.objects.exclude(working_hours=""):
        if (court.description or "").strip():
            continue
        court.description = f"Время работы: {court.working_hours}"
        to_update.append(court)
    if to_update:
        Court.objects.bulk_update(to_update, ["description"])


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0015_merge_parking_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="working_hours",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Например: 7:00 до 23:00",
                max_length=255,
                verbose_name="Время работы",
            ),
        ),
        migrations.RunPython(
            copy_working_hours_from_description,
            restore_working_hours_into_description,
        ),
    ]
