# Generated by Django 6.0.1 on 2026-09-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0016_court_working_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="racket_rental",
            field=models.BooleanField(default=False, verbose_name="Прокат инвентаря"),
        ),
    ]
