# Generated by Django 6.0.1 on 2026-09-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0017_alter_court_racket_rental_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Населённый пункт"),
        ),
        migrations.AlterField(
            model_name="courtapplication",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Населённый пункт"),
        ),
    ]
