# Generated by Django 6.0.1 on 2026-09-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0019_canonical_court_surfaces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                help_text="Латиница или кириллица. Если пусто в админке — заполнится из названия.",
                unique=True,
                verbose_name="URL",
            ),
        ),
    ]
