# Generated by Django 6.0.1 on 2026-09-03 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_locality_settlement_types"),
        ("courts", "0020_court_slug_allow_unicode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="district",
            field=models.CharField(blank=True, max_length=100, verbose_name="Район"),
        ),
        migrations.AlterField(
            model_name="court",
            name="geo_area",
            field=models.ForeignKey(
                blank=True,
                help_text="Зона Москвы или город области, из справочника. Поле «Район» — свободный текст.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courts",
                to="core.geoarea",
                verbose_name="Зона / город",
            ),
        ),
    ]
