# Generated by Django 6.0.1 on 2026-09-21 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_rename_zone_to_district"),
        ("courts", "0021_rename_city_verbose_to_locality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="geo_area",
            field=models.ForeignKey(
                blank=True,
                help_text="Район Москвы или город области, из справочника. Поле «Район» — более точное место свободным текстом.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courts",
                to="core.geoarea",
                verbose_name="Район / город",
            ),
        ),
        migrations.AlterField(
            model_name="court",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[("moscow", "Москва"), ("moscow_oblast", "Московская область")],
                db_index=True,
                default="",
                help_text="Москва или область. Определяет набор доступных районов и городов.",
                max_length=32,
                verbose_name="Регион",
            ),
        ),
    ]
