# Generated by Django 6.0.1 on 2026-09-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0022_rename_zone_to_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="has_glass_walls",
            field=models.BooleanField(
                default=False,
                help_text="Типично для падел-корта.",
                verbose_name="Стеклянные стены",
            ),
        ),
        migrations.AddField(
            model_name="court",
            name="padel_surfaces",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Искусственная трава, Mondo или другое.",
                verbose_name="Покрытие падел-корта",
            ),
        ),
        migrations.AddField(
            model_name="court",
            name="venue_sport",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tennis", "Теннис"),
                    ("padel", "Падел"),
                    ("both", "Теннис и падел"),
                ],
                db_index=True,
                default="tennis",
                help_text="Теннис, падел или оба. Падел-корт не смешивается с хардом и грунтом.",
                max_length=20,
                verbose_name="Вид спорта площадки",
            ),
        ),
        migrations.AddField(
            model_name="courtapplication",
            name="has_glass_walls",
            field=models.BooleanField(default=False, verbose_name="Стеклянные стены"),
        ),
        migrations.AddField(
            model_name="courtapplication",
            name="padel_surfaces",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Покрытие падел-корта"
            ),
        ),
        migrations.AddField(
            model_name="courtapplication",
            name="venue_sport",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tennis", "Теннис"),
                    ("padel", "Падел"),
                    ("both", "Теннис и падел"),
                ],
                default="tennis",
                max_length=20,
                verbose_name="Вид спорта площадки",
            ),
        ),
    ]
