# Generated by Django 6.0.1 on 2026-02-05 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_add_user_bot_chat_id'),
        ('tournaments', '0022_add_deadline_extension_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineExtensionRequestProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Запрос продления дедлайна',
                'verbose_name_plural': 'Запросы продления дедлайна',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tournaments.deadlineextensionrequest',),
        ),
        migrations.CreateModel(
            name='UserTelegramLinkProxy',
            fields=[
            ],
            options={
                'verbose_name': 'привязка Telegram',
                'verbose_name_plural': 'привязки Telegram',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.usertelegramlink',),
        ),
        migrations.CreateModel(
            name='TelegramBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Поддерживается HTML: <b>, <i>, <a href="...">', verbose_name='Текст сообщения')),
                ('image', models.ImageField(blank=True, help_text='Необязательно. Если указано — отправляется как пост с подписью.', null=True, upload_to='telegram_broadcasts/%Y/%m/', verbose_name='Фото')),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'рассылка в Telegram',
                'verbose_name_plural': 'рассылки в Telegram',
                'ordering': ('-created_at',),
            },
        ),
    ]
