# Generated by Django 6.0.1 on 2026-02-12 17:43

from django.db import migrations, models

import config.validators


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0001_add_telegram_broadcast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambroadcast",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Необязательно. Если указано — отправляется как пост с подписью. До 500 КБ, при загрузке сжимается.",
                null=True,
                upload_to="telegram_broadcasts/%Y/%m/",
                validators=[config.validators.validate_image_max_2mb],
                verbose_name="Фото",
            ),
        ),
    ]
